### ISSUE TITLE
IDBObjectStore does not export iterate anymore

### ISSUE THREAD

**Issue by Ptival** [jakearchibald/idb#102]
I'm guessing this is because we are in a transition phase to IndexedDB 2.0, but some of the type definitions are no longer valid.

For instance:
https://github.com/jakearchibald/idb/blob/809a75ccc31c46ac62174ff9c2c10efffa5a53df/lib/entry.ts#L647-L653
is no longer exposed.

See:
https://w3c.github.io/IndexedDB/#object-store-interface

**Comment by jakearchibald** [comment]
See the docs https://github.com/jakearchibald/idb/blob/master/README.md#async-iterators
