### ISSUE TITLE
Is it possible to bulk add?

### ISSUE THREAD

**Issue by andyjessop** [jakearchibald/idb#107]
I'm adding several thousand records at once and it gets quite slow - is it possible to bulk add records and receive only one Promise in return?

**Comment by jakearchibald** [comment]
What method are you currently using?

Does the performance problem go away if you [unwrap](https://github.com/jakearchibald/idb#unwrap) and use plain idb?

**Comment by andyjessop** [comment]
I was using `add`, but I've just seen `transaction`, which I think will do what I want:
```
   const tx = db.transaction('articles', 'readwrite');
    tx.store.add({
      title: 'Article 2',
      date: new Date('2019-01-01'),
      body: '…',
    });
    tx.store.add({
      title: 'Article 3',
      date: new Date('2019-01-02'),
      body: '…',
    });
    await tx.done;
```

**Comment by andyjessop** [comment]
If not, I'll check out `unwrap`.

**Comment by jakearchibald** [comment]
That should be loads faster. Let me know (and reopen this issue) if it's still significantly slow compared to the unwrapped version
