### ISSUE TITLE
Support of SSR (angular universal) with IDB package.

### ISSUE THREAD

**Issue by Pardeep9stacks** [jakearchibald/idb#108]
Trying to use this package with Angular universal but facing this issue.

`ReferenceError: IDBIndex is not defined`

Probably this is not working on server, Can someone provide a possible workaround for this? Do I need to 

`import { openDb, deleteDb } from 'idb';`

conditionally? or something else.

**Comment by jakearchibald** [comment]
Which version of the library are you using? It shouldn't throw on importing, even in a node environment.

It might throw if you try and use it. In which case feature-detect it with something like `if (self.indexedDB)`

**Comment by waseber** [comment]
I'm experiencing the same issue with Nuxt. I'm using IDB 4.0.3
The error specifically mentions the file node_modules\idb\build\cjs\index.js  on line 15
`const request = indexedDB.open(name, version);`

**Comment by waseber** [comment]
FWIW, I ended up using regular IndexedDB but wrapping that component in Nuxt <no-ssr></no-ssr> tags.

**Comment by Pardeep9stacks** [comment]
@jakearchibald I am using IDB v3.0.2. Facing this issue while using with Angular Universal.

**Comment by jakearchibald** [comment]
Could someone create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem for me to debug?

**Comment by ngocsangyem** [comment]
@jakearchibald  This issue happens when I try to build my project in SSR ( Angular Universal ). Then I solve it by adding this condition in ts file:

```javascript
isBrowser;
constructor(@Inject(PLATFORM_ID) private platformId) { 
   this.isBrowser = isPlatformBrowser(platformId);
}
if (this.isBrowser) { 
  // put your code which is access window variable 
} 
```
 Check this out: https://github.com/angular/universal/issues/830

**Comment by jakearchibald** [comment]
Closing this. Happy to look at it if a minimal example can be provided. A minimal example includes only the things needed to recreate the issue, and has instructions for how to recreate the issue.
