### ISSUE TITLE
iterateCursor

### ISSUE THREAD

**Issue by alexisargyris** [jakearchibald/idb#11]
Thanks for your excellent library, it's convenient and works well.

My problem is with your "iterateCursor" function. I am trying to use it like this:

```js
getSomeData(store) {
  let results = [];

  return DBPROMISE
    .then((db) => {
      const tx = db.transaction([store]);
      tx.objectStore([store]).iterateCursor(cursor => {
        if (!cursor) return;
        results.push(cursor.value);
        cursor.continue();
      });
      return tx.complete.then(() => { return results; });
    });
}
```

The above code, which, I believe, should work under all browsers, does work in Chrome Canary v.56 (i.e. it returns data) but doesn't work (i.e. returns no data) in normal Chrome v.54 or Firefox v.47. What am I missing?

**Comment by jakearchibald** [comment]
http://jsbin.com/kuzaqe/edit?js,console - seems to work fine.

Can you create an example that doesn't work?

**Comment by alexisargyris** [comment]
I think that [this ](http://jsbin.com/gonoci/edit?js,console) is equivalent to what I'm trying to do.

**Comment by jakearchibald** [comment]
Your second return statement in `getSomeData` will never run.

Here's a fixed example http://jsbin.com/jerawi/edit?js,console - works in Chrome and Firefox.

**Comment by alexisargyris** [comment]
Thanks for that however it seems that some detail is still not obvious to me.

```
  getAsync(os, projectId, key) {
    // return the requested items
    let results = [];

    return DBPROMISE
      .then((db) => {
        const lowerBound = [projectId, '0000000000000000000000000000000000000000'];
        const upperBound = [projectId, 'ffffffffffffffffffffffffffffffffffffffff'];
        const range = IDBKeyRange.bound(lowerBound, upperBound);
        const tx = db.transaction([os]);
        tx.objectStore([os]).iterateCursor(range, cursor => {
          if (!cursor) return;
          results.push(cursor.value);
          cursor.continue();
        });
        return tx.complete;
      }).then(() => {
        LOGGER.info(results.length);
        return results;
      });
  }
```

This code (untouched) is simultaneously executed by Chrome and Firefox. Chrome logs a number > 0 while Firefox displays 0. What is going on?

**Comment by jakearchibald** [comment]
Can you create a JSBin that demonstrates the problem?

**Comment by alexisargyris** [comment]
False alarm, fixed it. Thanks a lot for your time!

**Comment by jakearchibald** [comment]
Haha, yep! Creating a reduced version of the problem usually reveals the bug 😄

**Comment by alexisargyris** [comment]
Exactly! Thanks again!
