### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by yurytomilin** [jakearchibald/idb#111]
Hello Jake!

I have a quick question - is it possible to use the package if I'm trying to support IE11 in my app?

Considering that there is no `Proxy` polyfill, should I consider other alternatives?

Thank you a lot and have a good one!

**Comment by jakearchibald** [comment]
https://github.com/jakearchibald/idb/tree/v3.0.2 - 3.0.2 doesn't have quite as many features, but it supports IE11.
