### ISSUE TITLE
Declaration not found when using `idb/with-async-ittr.js`

### ISSUE THREAD

**Issue by Fnxxxxo** [jakearchibald/idb#113]
The type system works fine when using `import { IDBPDatabase, openDB } from 'idb'`, but fall when changed to `import { IDBPDatabase, openDB } from 'idb/with-async-ittr'`. I try to include the index.d.ts directly in the tsconfig but not works.
I am using webstorm. Any way to walk around?

**Comment by mariusGundersen** [comment]
I'm having the same problem :(

**Comment by mariusGundersen** [comment]
I found a workaround:

```ts
import { openDB, DBSchema } from 'idb';
import { } from 'idb/lib/async-iterators';
```

This is pretty much what the `with-async-ittr.ts` file would contain to make it work.

**Comment by Fnxxxxo** [comment]
@mariusGundersen Nice work. But sames wired.

**Comment by SebastianSpeitel** [comment]
I'm having the same issue, but the workaround doesn't work for me, because rollup just ignores it during treeshaking.

To add the missing typefile would still be the best solution.
Otherwise if anyone has another workaround, I would be grateful.
