### ISSUE TITLE
promisyRequest prints Uncaught Promise exceptions

### ISSUE THREAD

**Issue by AlexGalays** [jakearchibald/idb#115]
Not a blocker but it can lead to a lot of noise in error tracking software:

Due to a detached `.then` at this line: https://github.com/jakearchibald/idb/blob/master/lib/wrap-idb-value.ts#L48

There's no way for call sites to cleanly catch all Promise errors.

It's effectively the same as this:

```ts
const x = new Promise((resolve, reject) => {
  reject(new Error('oh no'));
})

// This statement will later print an error
x.then(x => console.log(x))

x.catch(err => {})
```

It's easy to reproduce by calling `openDB()` on a tiny partition, or simply rejecting the Promise.

**Comment by jakearchibald** [comment]
Published as 4.0.4. Thanks for the suggestion!

**Comment by AlexGalays** [comment]
That was fast! Thanks

**Comment by AlexGalays** [comment]
This line can also print an error:

https://github.com/jakearchibald/idb/blob/master/lib/entry.ts#L56

There might be others (sorry, I don't know the codebase all that much)

**Comment by costicaaa** [comment]
Hi, I am getting the Uncaught (in promise) DOMException as well. Tried to debug on my end with no luck, and it seems it leads to this 
https://github.com/jakearchibald/idb/blob/e27db4fa66c593f5eff5d68d8138a75028409b56/lib/database-extras.ts#L35

Much appreciated if you can take a look :) 
Thanks

**Comment by costicaaa** [comment]
this seem to does the trick for me, not sure if I am missing something else tho 
```js
if (isWrite)
            try
            {
                await tx.done;
                return returnVal;
            }
            catch(err){
                
            }
```

tried modifying this in the build/esm/index.js

**Comment by jakearchibald** [comment]
That doesn't look right to me. Seems like you've miss real transaction errors.

**Comment by costicaaa** [comment]
Yeah, I messed up some params when calling .get and it was confusing as hell for both me and the library :) 

All good, thanks for the response

**Comment by QNimbus** [comment]
If found another instance where you get an 'Uncaught Promise' exception. If you call `openDB` with the `blocking` callback function :

My code:

```
this.db = await openDB(this.storeName, ObjectModel.currentVersion(), {
            upgrade: (db, oldVersion, newVersion, transaction) => {
                    // my code....
                    // my code....
                    // my code....
            },
            blocked() {
                this.emitToListeners("warning", "This connection is blocked by previous versions of the database");
            },
            blocking() {
                this.emitToListeners("warning", "This connection is blocking a future version of the database from opening");
            }
```

Location of the problem in the `idb` source code : 

```
function openDB(name, version, { blocked, upgrade, blocking } = {}) {
    const request = indexedDB.open(name, version);
    const openPromise = wrap(request);
    if (upgrade) {
        request.addEventListener('upgradeneeded', (event) => {
            upgrade(wrap(request.result), event.oldVersion, event.newVersion, wrap(request.transaction));
        });
    }
    if (blocked)
        request.addEventListener('blocked', () => blocked());
    if (blocking)
        openPromise.then(db => db.addEventListener('versionchange', blocking));
    return openPromise;
}
```

Specifically this part => `openPromise.then(db => db.addEventListener('versionchange', blocking));`

I can reproduce this problem by calling the `openDB` method with a lower version number than I had previously used, therefore triggering an exception in the `blocking` callback.

I presume this can be easily fixed by implementing the same solution as before?

```
// Catching to avoid "Uncaught Promise exceptions"
    }).catch(() => { });
```

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/idb/issues/127
