### ISSUE TITLE
Jest testing for my library using idb

### ISSUE THREAD

**Issue by aneer-anwar** [jakearchibald/idb#117]
Jest uses JSDOM to fake dom elements but unfortunately, Indexeddb support is only in their timeline and not implemented. One workaround is to include 'fake-indexeddb' module . but 'idb' module looks for window .indexeddb. Is there any way to test 'idb'  using jest?

**Comment by jakearchibald** [comment]
This library is a wrapper around IDB. It's 100% dependent on an IDB implementation. You could run your tests in something like Puppeteer.

**Comment by aneer-anwar** [comment]
ok thank you

**Comment by aneer-anwar** [comment]
FYI. I could do the browser testing using Karma + jasmine + rollup. If anyone is interested I can share the code.
