### ISSUE TITLE
DeleteDB not working. Angular 7

### ISSUE THREAD

**Issue by abizit** [jakearchibald/idb#118]
I am using it on Angular 7 and i am not able to delete the DB.
This is how i am trying to run it in Typescript.
 ```
 async deleteDatabase() {
        return await deleteDB(this.dbName);
    }
```
I am not being able to make it work.
When i use the vanilla way using indexedDB.deleteDatabase(name); it says blocked.

**Comment by jakearchibald** [comment]
You need to close all connections before the database can be deleted.

**Comment by geoidesic** [comment]
Fair enough but there's nothing in the docs about how to close a database? Also this doesn't cause any errors.. just nothing happens.

**Comment by abizit** [comment]
> Fair enough but there's nothing in the docs about how to close a database? Also this doesn't cause any errors.. just nothing happens.

I got it working like this..

```
const db = await openDB(name, version, { ... });
db.close();
await deleteDB();
```

**Comment by ivanjeremic** [comment]
> > Fair enough but there's nothing in the docs about how to close a database? Also this doesn't cause any errors.. just nothing happens.
> 
> I got it working like this..
> 
> ```
> const db = await openDB(name, version, { ... });
> db.close();
> await deleteDB(name);
> ```

Where is `deleteDB(name)` coming from?
