### ISSUE TITLE
IDB cursor delete only deletes first record in ios safari

### ISSUE THREAD

**Issue by aneer-anwar** [jakearchibald/idb#123]
idb cursor delete works as expected in every other device but fails in ios safari . safari deletes only first record.

  let cursor :IDBPCursorWithValue= await this.getCursor(columnMatch);
         while (cursor) {
            cursor.delete();
            cursor = await cursor.continue();
         }
         return true;

  cursor gets null value on the second iteration. Please have a look.

**Comment by justjake** [comment]
How is `this.getCursor(columnMatch);` implemented? The issue could be there.

**Comment by jakearchibald** [comment]
Could you create a reduced demo of the issue on glitch.com, jsbin.com, or similar? I think it might just be a Safari bug, but I'd like to double check.

**Comment by jakearchibald** [comment]
Closing due to no reduced demo.
