### ISSUE TITLE
Ability to iterate over cursor without await method

### ISSUE THREAD

**Issue by mohit-sentieo** [jakearchibald/idb#126]
I would like to iterate over a cursor. But unfortunately our large code base does not use async/await and this is causing a problem. I have decided to do something like this
[https://gist.github.com/mohit-sentieo/e161aa4fe5ac0eb1cbfb2579b62fb5f4](url)

But this doesn't seem to be working. There should be a way to iterate over cursor without Promise recursion.

**Comment by jakearchibald** [comment]
Without async/await I would do this:

```js
db.transaction(storeName).store.openCursor().then(function handleCursor(cursor) {
  console.log(cursor.key, cursor.value);
  return cursor.continue().then(handleCursor);
}).then(() => {
  console.log('done!');
});
```

Please reopen if that isn't the answer you're looking for!
