### ISSUE TITLE
Cannot creat objectStore

### ISSUE THREAD

**Issue by rostgoat** [jakearchibald/idb#134]
```
const db = await openDB('db', 1, {
    upgrade(db) {
      db.createObjectStore('BobsYourUncle', { keyPath: 'id', autoIncrement: true });
    },
  });
```

I am expecting to see `BobsYourUncle`inside the `objectStoreNames` Array in browser but it's an empty list.. why?

![Screenshot from 2019-10-25 12-31-26](https://user-images.githubusercontent.com/22672124/67598828-6744f800-f723-11e9-9371-c6e4b05e13f9.png)

if I attempt to add data to store
```
await db.add('user', { firstname: 'John', lastname: 'Doe', age: 33 });
```
I get
```
DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```
cuz store doesnt exist...

**Comment by jakearchibald** [comment]
https://output.jsbin.com/vipanum/ - here's a working example very similar to your code above.

I suspect you changed your `upgrade` callback but didn't change the version number of the database. `upgrade` only runs when the version number changes.

Please reopen this if you can create an example of the issue you're seeing.
