### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by kumaravelcrayond** [jakearchibald/idb#142]
When i use npm run build the following is recurred but when i use npm start the build is working fine.

Failed to minify the code from this file:

    ./node_modules/idb/build/esm/index.js:11

the code at that line number is:

openDB function

help me to solve this error issue.

thank you

**Comment by jakearchibald** [comment]
Minifying using terser is working fine for me. Can you give me more concrete steps to reproduce the issue and reopen this?
