### ISSUE TITLE
An aborted transaction should not throw null

### ISSUE THREAD

**Issue by birtles** [jakearchibald/idb#144]
Currently for both `error` and `abort` events, transactions run the same event handler (see [this code](https://github.com/jakearchibald/idb/blob/12f14cbac34207cc13cf6ec8369ec36a1ef9ea91/lib/wrap-idb-value.ts#L107-L113)):

```ts
const error = () => {
  reject(tx.error);
  unlisten();
};
// ...
tx.addEventListener('error', error);
tx.addEventListener('abort', error);
```

However, when a transaction is aborted, `tx.error` may be `null` as per [the spec](https://w3c.github.io/IndexedDB/#dom-idbtransaction-abort).

Having `await tx.done` throw `null` is a bit confusing. Perhaps we should have a separate event handler for `abort` that rejects with an `AbortError` if `tx.error === null`?

**Comment by jakearchibald** [comment]
Agreed. AbortError is the right thing here.
