### ISSUE TITLE
index.iterate is not a function

### ISSUE THREAD

**Issue by silkwromzf** [jakearchibald/idb#146]
run Examples Article store
throw  error  index.iterate is not a function
`"dependencies": {
    "core-js": "^3.4.3",
    "element-ui": "^2.4.5",
    "idb": "^4.0.5",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-plugin-pwa": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-element": "^1.0.1",
    "vue-template-compiler": "^2.6.10"
  },`

**Comment by jakearchibald** [comment]
See https://github.com/jakearchibald/idb#async-iterators
