### ISSUE TITLE
Renaming store in transaction throws error

### ISSUE THREAD

**Issue by mustafa0x** [jakearchibald/idb#147]
```js
const store = transaction.objectStore('old-name');
// TypeError: Illegal invocation
store.name = 'new-name';
// Works (no error; renames the objectStore)
unwrap(store).name = 'new-name';
```

**Comment by jakearchibald** [comment]
Demo: https://static-misc-2.glitch.me/idb/store-rename.html

https://github.com/jakearchibald/idb/blob/master/lib/wrap-idb-value.ts#L120 - I need to add a set trap.

**Comment by jakearchibald** [comment]
Thanks for reporting this!

The only assignable things are `name` (on both stores and indexes), and event handlers. I guess I should just let all assignment through and let the underlying object deal with it.
