### ISSUE TITLE
incorrect multientry index typings

### ISSUE THREAD

**Issue by akhilpai** [jakearchibald/idb#153]
Hello, it seems multiEntry index typings are incorrect.

For example, given a schema:
`entries: {
   key: string
   value: { tags: string[] }
   indexes
 }`

created as:
`
const store = db.createObjectStore("entries")
`
`
store.createIndex("tags", "tags", { multiEntry: true })
`

Retrieval by
`
await db.getFromIndex("entries", "tags", ["some tag"])
`
returns an empty array

while
`
await db.getFromIndex("entries", "tags", "some tag")
`
fails with a cast error.

and
`
await db.getFromIndex("entries", "tags", ("some tag" as unknown) as string[])
`
returns desired data.

**Comment by jakearchibald** [comment]
Can you give me a full reduced code sample?

**Comment by akhilpai** [comment]
Sure, try removing the cast at: https://github.com/akhilpai/idb-153/blob/master/src/example.ts

I did not expect the error:
`Argument of type '"some tag"' is not assignable to parameter of type 'string[] | IDBKeyRange | undefined'.`

**Comment by jakearchibald** [comment]
Just to keep things in the thread:

```ts
import { DBSchema, openDB } from "idb";

interface Schema extends DBSchema {
    entries: {
        key: string;
        value: { id: string; tags: string[] };
        indexes: { tags: string[] };
    };
}

(async () => {
    let db = await openDB<Schema>("entryDB", 1, {
        async upgrade(db) {
            const entryStore = db.createObjectStore("entries", { keyPath: "id" });
            entryStore.createIndex("tags", "tags", {
                multiEntry: true
            });
        }
    });

    await db.add("entries", { id: "some id", tags: ["some tag"] });

    let result = await db.getAllFromIndex(
        "entries",
        "tags",
        ("some tag" as unknown) as string[]
    );

    console.log(result);
})();
```

**Comment by jakearchibald** [comment]
Shouldn't your index type `string` rather than `string[]`?

```ts
interface Schema extends DBSchema {
    entries: {
        key: string;
        value: { id: string; tags: string[] };
        indexes: { tags: string };
    };
}
```

**Comment by akhilpai** [comment]
Yes, you are right. Thank you for investigating and sorry for the noise!

**Comment by jakearchibald** [comment]
No worries! Glad folks are finding the typings useful.
