### ISSUE TITLE
Idb does not work on iOS browsers

### ISSUE THREAD

**Issue by webstermath** [jakearchibald/idb#156]
When idb is used in iOS browsers, the following error is thrown: 

`undefined is not an object (evaluating 'request')`

I created the following pen to demonstrate this error. Just run in any iOS browser:

https://codepen.io/webstermath/pen/LYEoRzX?editors=0012

**Comment by jakearchibald** [comment]
Unfortunately Safari now disables browser storage when your page is within an iframe. You need to call their non-standard API to enable it https://webkit.org/blog/8124/introducing-storage-access-api/.

By the way, you're using a pretty old version of the library.
