### ISSUE TITLE
AbortError: AbortError

### ISSUE THREAD

**Issue by geoidesic** [jakearchibald/idb#166]
I'm getting an error like this:
```
Vue warn]: Error in v-on handler (Promise/async): "AbortError: AbortError"
```
No other information given.
I'm simply trying `db.instance.add("<storageName>", payload)`. The DB exists. How can I get more information about what's wrong?

**Comment by piotr-cz** [comment]
Same here, would be nice to get at least stack trace.
For met his sometimes happens when payload overwrites existing entry (`keyPath` is present in store)

**Comment by jakearchibald** [comment]
I dunno if I'd expect that to be an abort error. I'm not sure what `db.instance` is either. Can either of you create a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of this issue?

**Comment by piotr-cz** [comment]
Error is thrown when you add an item with existing keyPath.
So the fix is to use `db.instance.put` instad of `db.instance.add`.

Problem is that developer is left with plain `AbortError` which is not very informative and there is no stack trace attached.

**Comment by jakearchibald** [comment]
I'm not sure what `db.instance` is. It isn't part of the library. Can you create a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of this issue?

**Comment by piotr-cz** [comment]
When looking at https://github.com/jakearchibald/idb/issues/166#issue-587870262 it's a `IDBDatabase` object (result of `openDB` method).

**Comment by jakearchibald** [comment]
Can either of you create a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of this issue?

That way I can see the actual error you're seeing, and start debugging it.

**Comment by chestozo** [comment]
Hey guys
I am also without a minimal reproduction case sorry.
Just some details of my case.

I have a webapp installed on iPhone under iOS 13.3.1 (but I am seeing this error for half a year maybe).
After I've switched to `idb` the error is just plain `AbortError` without any details and stack trace.
Before when I was working with indexedDB directly it was something like
```
Connection to Indexed Database server lost. Refresh the page to try again
```
I was investing it sometime ago and at that point I've switched to `idb`.
One more detail: after I receive the first `AbortError` I try to reopen connection to database but it just stops working.
Only full webapp restart helps.

Maybe it is related to this issue https://bugs.webkit.org/show_bug.cgi?id=197050

**Comment by jakearchibald** [comment]
Ok, it'd have been nice if someone had created a minimal reproduction, but I've gone ahead and created one myself https://static-misc-2.glitch.me/idb/add-error.html

If I've reproduced the same error you're seeing, it seems like I need to fix the shortcut methods so the rejection of the request takes priority over the transaction.

**Comment by jakearchibald** [comment]
I think the fix is as simple as https://github.com/jakearchibald/idb/commit/24e7d91cae412f4205a9cf8d5cfd9ab56fc7f311 - which means the error from the `put`/`add`/whatever takes priority over the error from the transaction.

Without a minimal reproduction from any of the reporters here, it's possible I'm tackling a completely different issue. If that's the case, please create a minimal reproduction of the issue you're seeing.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/idb/pull/181 and published as 5.0.3.

If this didn't solve the issue, please reopen, but I won't fix anything without a minimal reproduction of the issue.

**Comment by mikkoh** [comment]
@jakearchibald we are still seeing this exception. It never has stack traces. In our application (Shopify Admin) it ends up being an uncaught exception even though in all call sites we are attempting to handle it.

**Comment by jakearchibald** [comment]
I don't suppose you could find a way to reproduce the error? Is it any particular browser/OS?
