### ISSUE TITLE
Just a question about push notifications

### ISSUE THREAD

**Issue by novaknole** [jakearchibald/idb#168]
Hi @jakearchibald  i know this topic is completely unrelated here and I know I shouldn't be asking it here, but since This is urgent for me and you're one of those guys that know so much  , I was wondering if you could shed a light on this one.

I am developing PWA. Now, I also want to use `push notifications`. But on safari ios, it's not available yet.  So, I have some questions.

Let's say user uses IOS device(iPHONE)

1) if that user goes to my PWA website using **chrome**, I guess push notifications will work flawlessly. right?

2) if that user goes to my PWA website using **safari**, i guess push notifications won't work right?

3) if User adds a website (`add to home screen`) from **chrome** and opens a app from menu, will push the notifications work?

4) if user adds a website (`add to home screen`) from  **safari** and opens an app from menu, will push notifications work?

5) is it even in development?  i couldn't find any information on this.

Sorry to be opening an issue about the completely unrelated topic. Thanks in advance.

**Comment by jakearchibald** [comment]
> * if that user goes to my PWA website using **chrome**, I guess push notifications will work flawlessly. right?

Apple doesn't allow other browser engines on iOS, so 'other browsers' on iOS are just Safari with some different UI. Therefore push is not available on Chrome on iOS.

> * if that user goes to my PWA website using **safari**, i guess push notifications won't work right?

Push is not available on Safari on iOS.

> * if User adds a website (`add to home screen`) from **chrome** and opens a app from menu, will push the notifications work?

Apple doesn't allow other browser engines on iOS, so 'other browsers' on iOS are just Safari with some different UI. Therefore push is not available on Chrome on iOS.

> * if user adds a website (`add to home screen`) from  **safari** and opens an app from menu, will push notifications work?

Push is not available on Safari on iOS.

> * is it even in development?  i couldn't find any information on this.

You'll have to ask Safari folks about that.
