### ISSUE TITLE
Targeting ES2017

### ISSUE THREAD

**Issue by adversinc** [jakearchibald/idb#170]
The module targets to esnext/ES2020 by default. Is it possible to lower the TypeScript target version to ES2017?

While modern browsers do support ES2020, we face issues with older Android 7 WebView. This version still widely used at the moment.

We've done a fork for now, but it would be good to stay with a main module branch.

**Comment by jakearchibald** [comment]
I've designed this module to target modern JS, but feel free to use Babel or similar to transpile the library for other targets.
