### ISSUE TITLE
store delete typing shows string

### ISSUE THREAD

**Issue by aakaul** [jakearchibald/idb#175]
I am using IDBPDatabase with ts 

```ts
async deleteIDB(key:string){
    const tx = this._db.transaction(this.dbName,"readwrite");
    const store = tx.objectStore(this.dbName);
    store.delete(key)
    return tx.done;
}
```

for the above code i had to keep key as string type because store.delete has (key: string | IDBKeyRange) typing but type string doesnt delete the entry..

the method store.delete works well with type number which is not assignable to store.delete

**Comment by jakearchibald** [comment]
I tried to recreate this but it works fine https://codesandbox.io/s/dank-silence-m4eld?file=/src/index.ts.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue.
