### ISSUE TITLE
Better way to handle ordering/sorting when getting from index 

### ISSUE THREAD

**Issue by belvederef** [jakearchibald/idb#176]
Thank you for the awesome work. I was wondering if a more straightforward way to handle ordering/sorting could be implemented. Currently, to get the results of an index in *ascending* order, I am doing:
```js
let cursor = await myDb
  .transaction('articles')
  .store.index('by-timestamp')
  .openCursor(undefined, 'prev');

const articles = []
while (cursor) {
  articles.push(cursor.value)
  cursor = await cursor.continue();
}
```
But wondering if an easier way could be implemented such that one could call:
```js
const articles = await myDb.getAllFromIndex(
  'articles',
  'by-timestamp',
  undefined,
  20, // count
  'ASC', // order
);
```
It looks to me like this is pretty commonly used, but maybe there are reasons for not having this feature.

**Comment by jakearchibald** [comment]
Ascending should be the default, no?

Getting things in reverse order from an index is already pretty easy:

```js
const articles = (await myDb.getAllFromIndex('articles', 'by-timestamp')).reverse();
```

**Comment by jakearchibald** [comment]
Please reopen this if it isn't the right answer!

**Comment by belvederef** [comment]
Sorry, yes ascending is the default, I meant descending order.

Your solution will work in case we are getting all the objects from the store but rarely you would want that. Anyhow, I think this issue needs to [first be implemented by the w3c folks](https://github.com/w3c/IndexedDB/issues/130).
