### ISSUE TITLE
NPM run build throwing errors

### ISSUE THREAD

**Issue by kuhlaid** [jakearchibald/idb#177]
I cloned the repo, ran an npm install and tried npm run build but the build will not execute due to error (Failed at the idb@5.0.2 build script). I would like to run the idb tests.

**Comment by jakearchibald** [comment]
I'll need more details than that

**Comment by jakearchibald** [comment]
Closing. Please reopen if you can provide enough details for me to recreate the problem you're having.

**Comment by kuhlaid** [comment]
I cloned this repo yesterday and was trying to perform the steps listed in the 'Building and testing' section of the README at the bottom of the page. It says to run 'npm run build', add a server to the build, then check the build/test/ directory in the browser. Of course without a build there is no build/test/ directory to test.

**Comment by jakearchibald** [comment]
You haven't told me anything about the platform or node version you're using.

**Comment by kuhlaid** [comment]
I'm on Windows 10 Enterprise 64bit running node v8.11.3. I can certainly update my node version if that is an issue. - thanks

**Comment by jakearchibald** [comment]
Yeah, it's likely to be the old node version. Maintenance on 8.x ended on 2019-12-31.
