### ISSUE TITLE
Anyone care to review my blog post which accidentally carries some responsibilities?

### ISSUE THREAD

**Issue by ZYinMD** [jakearchibald/idb#179]
As a by-product of teaching myself how to use idb, I wrote a [very long and very detailed tutorial](https://hackernoon.com/use-indexeddb-with-idb-a-1kb-library-that-makes-it-easy-8p1f3yqq) on learning indexeddb and idb together for new developers. Before I knew it, it became the highest ranking blog post on google search, and the 1st result after a few official docs:

![image](https://user-images.githubusercontent.com/32368482/80555933-d97ee980-899f-11ea-957a-98f156a56f34.png)

Since it may get a lot of traffic, I really don't want to mislead any readers by providing any wrong information when they're first time learners. So, if any of our maintainers here would like to read it, and point out any mistakes I made so I can fix it, I'd really appreciate it!

**Comment by jakearchibald** [comment]
Looks good to me! Although the code samples are hard to read (might be a dark mode issue)

<img width="690" alt="Screenshot 2021-01-06 at 14 36 37" src="https://user-images.githubusercontent.com/93594/103780249-a4e22800-502c-11eb-8378-f824958c7e7e.png">
