### ISSUE TITLE
polyfill getAllKeys for EDGE & IE 

### ISSUE THREAD

**Issue by litt1e-p** [jakearchibald/idb#180]
why not implement polyfill `getAllKeys` for EDGE & IE on tag `v3.0.x`? just like [polyfill getAll](https://github.com/litt1e-p/idb/tree/v3.0.3)

**Comment by jakearchibald** [comment]
I didn't want to bloat the library for folks that were using modern browsers. The library doesn't support IE from 4.x onwards due to reliance on proxy objects.

Edge supports `getAllKeys` from 79 onwards.

**Comment by jakearchibald** [comment]
Oh, I just realised you're asking specifically for an addition to `3.x`. Um, I guess I felt it wasn't common enough to add. You're the first person asking for it.

**Comment by litt1e-p** [comment]
yeah, idb is great. I am using it in vue 2.6.x, my project must support Edge 44+ & IE for some reasons. I had tried to make a pull request with tag `v3.0.3`, but failed.

**Comment by lucaluca** [comment]
For Edge specifically, I''m using [indexeddb-getall-shim](https://www.npmjs.com/package/indexeddb-getall-shim) with idb@5 and it works fine on Edge v44. Edge doesn't have `getKey` but you can just use `count` instead.

**Comment by jakearchibald** [comment]
I'm not actively maintaining the old versions (although I'll fix bugs in some cases), so I'm going to close this.
