### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase

### ISSUE THREAD

**Issue by pinal-r** [jakearchibald/idb#182]
Unhandled Rejection (NotFoundError): Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

Facing this error. 
My code is 

```
const DB_NAME=`language_${window.localStorage.getItem('accountcode') || 0}`;
const langDB=openDB('abs2anguage', 1, {
    upgrade(db) {
        db.createObjectStore(DB_NAME);
    },
});
```

**Comment by aman8604** [comment]
I am also facing the same issue

**Comment by jakearchibald** [comment]
In the code example above, `DB_NAME` is used as the store name, which is weird. It means that the store name could change without changing the schema version of the database. If that happens, you'll try to get an object store that was never created.

**Comment by jakearchibald** [comment]
If that isn't the issue, please create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue, and I'll take a look.

**Comment by isaacdarcilla** [comment]
Got the same issue.

**Comment by jakearchibald** [comment]
@isaacdarcilla Please create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue, and I'll take a look.

**Comment by isaacdarcilla** [comment]
It's working now.
