### ISSUE TITLE
Dump all objects

### ISSUE THREAD

**Issue by septs** [jakearchibald/idb#191]
```ts
const databases = (await indexedDB.databases?.()) ?? []
for (const { name, version } of databases) {
  const db = await openDB(name, version)
  const stores: Record<string, unknown[]> = {}
  for (const name of db.objectStoreNames) {
    stores[name] = await db.getAll(name)
  }
  console.log(name, version, stores)
}
```

Cannot read the second database

![image](https://user-images.githubusercontent.com/3842474/89490398-662b1600-d7df-11ea-8a7f-ed131fa78f63.png)

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/89498476-e4dc7f00-d7f0-11ea-9217-bb4e47875658.png)

`openDB` need design a open timeout options

**Comment by jakearchibald** [comment]
I tried to piece together a reduced example: https://static-misc-2.glitch.me/idb/two-databases-bug.html

It seems to work fine.

Please reopen when you have a reduced example that shows the issue.
