### ISSUE TITLE
openDB version parameter should be optional

### ISSUE THREAD

**Issue by asiaracz** [jakearchibald/idb#196]
In the original indexedDB API, the _version_ parameter of the _open_ function is optional:
https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/open

It would be good if the openDB function also allowed not passing the version.

**Comment by enguerran** [comment]
I came across this need.
Glad to see that a ticket has already been opened and that there is even a PR to correct the library.

I checked if the PR was released and found `5.0.5` to have this change: https://github.com/jakearchibald/idb/blob/v5.0.5/src/entry.ts#L45

but not in builds:
- https://github.com/jakearchibald/idb/blob/v5.0.5/build/esm/entry.d.ts#L35
- https://github.com/jakearchibald/idb/blob/v5.0.5/build/cjs/entry.d.ts#L35

Is it an oversight or are builds delivered later?

**Comment by jakearchibald** [comment]
This is an oversight. Thanks for the heads-up. I'll fix it.

**Comment by jakearchibald** [comment]
Published as 5.0.6.
