### ISSUE TITLE
Multiple concurrent transactions slow

### ISSUE THREAD

**Issue by mfbx9da4** [jakearchibald/idb#199]
I am building a react app which has multiple views. Each view fetches the data it needs from IDB to render. Sometimes it fetches from the same table in different views. Also concurrently I am fetching data from the network and inserting data into IDB. I am experiencing queries taking up to 400ms. Presumably the issue is this (from the readme)

> Do not await other things between the start and end of your transaction

Am I using IDB totally wrong? I am not supposed to use IDB as the primary store in the app and instead use it only on initial boot? I don't see how I can avoid doing other concurrent stuff while fetching.

**Comment by jakearchibald** [comment]
I can't debug this without a minimal reproducable example https://stackoverflow.com/help/minimal-reproducible-example. It seems unlikely that the speed issues are due to this library, but I'll happily reopen the issue and a look if you can provide an example.

**Comment by mfbx9da4** [comment]
```
window.timer = async fn => {
    const start = Date.now()
    const res = await fn()
    const end = Date.now()
    return [end - start, res]
  }
  window.a = async () => {
    const [took, res] = await window.timer(() => window.db.getAll('messages'))
    console.log('took, res.length', took, res.length)
  }
  window.b = async () => {
    for (let i = 0; i < 100; i++) {
      await window.a()
    }
  }
  window.c = async () => {
    await Promise.all([...Array(100)].map(window.a))
  }
```
calling `b()`

```
took, res.length 41 2915
queries.js?56c3:22 took, res.length 40 2915
queries.js?56c3:22 took, res.length 38 2915
queries.js?56c3:22 took, res.length 36 2915
queries.js?56c3:22 took, res.length 34 2915
queries.js?56c3:22 took, res.length 36 2915
queries.js?56c3:22 took, res.length 33 2915
.... all around this time
```

calling `c()`

```
took, res.length 62 2915
queries.js?56c3:22 took, res.length 74 2915
queries.js?56c3:22 took, res.length 89 2915
queries.js?56c3:22 took, res.length 104 2915
queries.js?56c3:22 took, res.length 120 2915
queries.js?56c3:22 took, res.length 140 2915
queries.js?56c3:22 took, res.length 163 2915
queries.js?56c3:22 took, res.length 183 2915
queries.js?56c3:22 took, res.length 209 2915
queries.js?56c3:22 took, res.length 228 2915
queries.js?56c3:22 took, res.length 249 2915
queries.js?56c3:22 took, res.length 269 2915
queries.js?56c3:22 took, res.length 292 2915
queries.js?56c3:22 took, res.length 314 2915
queries.js?56c3:22 took, res.length 333 2915
queries.js?56c3:22 took, res.length 356 2915
queries.js?56c3:22 took, res.length 375 2915
queries.js?56c3:22 took, res.length 399 2915
queries.js?56c3:22 took, res.length 419 2915
queries.js?56c3:22 took, res.length 466 2915
queries.js?56c3:22 took, res.length 506 2915
queries.js?56c3:22 took, res.length 543 2915
queries.js?56c3:22 took, res.length 586 2915
queries.js?56c3:22 took, res.length 625 2915
queries.js?56c3:22 took, res.length 671 2915
queries.js?56c3:22 took, res.length 702 2915
queries.js?56c3:22 took, res.length 717 2915
queries.js?56c3:22 took, res.length 739 2915
queries.js?56c3:22 took, res.length 758 2915
queries.js?56c3:22 took, res.length 772 2915
queries.js?56c3:22 took, res.length 784 2915
queries.js?56c3:22 took, res.length 800 2915
queries.js?56c3:22 took, res.length 815 2915
queries.js?56c3:22 took, res.length 828 2915
queries.js?56c3:22 took, res.length 840 2915
queries.js?56c3:22 took, res.length 856 2915
queries.js?56c3:22 took, res.length 875 2915
queries.js?56c3:22 took, res.length 912 2915
queries.js?56c3:22 took, res.length 929 2915
queries.js?56c3:22 took, res.length 945 2915
queries.js?56c3:22 took, res.length 962 2915
queries.js?56c3:22 took, res.length 983 2915
queries.js?56c3:22 took, res.length 1004 2915
queries.js?56c3:22 took, res.length 1027 2915
queries.js?56c3:22 took, res.length 1051 2915
queries.js?56c3:22 took, res.length 1071 2915
queries.js?56c3:22 took, res.length 1099 2915
queries.js?56c3:22 took, res.length 1119 2915
queries.js?56c3:22 took, res.length 1140 2915
queries.js?56c3:22 took, res.length 1162 2915
queries.js?56c3:22 took, res.length 1184 2915
queries.js?56c3:22 took, res.length 1207 2915
queries.js?56c3:22 took, res.length 1226 2915
queries.js?56c3:22 took, res.length 1251 2915
queries.js?56c3:22 took, res.length 1269 2915
queries.js?56c3:22 took, res.length 1292 2915
queries.js?56c3:22 took, res.length 1314 2915
queries.js?56c3:22 took, res.length 1335 2915
queries.js?56c3:22 took, res.length 1386 2915
queries.js?56c3:22 took, res.length 1421 2915
queries.js?56c3:22 took, res.length 1462 2915
queries.js?56c3:22 took, res.length 1509 2915
queries.js?56c3:22 took, res.length 1550 2915
queries.js?56c3:22 took, res.length 1592 2915
queries.js?56c3:22 took, res.length 1626 2915
queries.js?56c3:22 took, res.length 1666 2915
queries.js?56c3:22 took, res.length 1677 2915
queries.js?56c3:22 took, res.length 1703 2915
queries.js?56c3:22 took, res.length 1713 2915
queries.js?56c3:22 took, res.length 1726 2915
queries.js?56c3:22 took, res.length 1743 2915
queries.js?56c3:22 took, res.length 1758 2915
queries.js?56c3:22 took, res.length 1771 2915
queries.js?56c3:22 took, res.length 1786 2915
queries.js?56c3:22 took, res.length 1800 2915
queries.js?56c3:22 took, res.length 1817 2915
queries.js?56c3:22 took, res.length 1835 2915
queries.js?56c3:22 took, res.length 1858 2915
queries.js?56c3:22 took, res.length 1882 2915
queries.js?56c3:22 took, res.length 1902 2915
queries.js?56c3:22 took, res.length 1926 2915
queries.js?56c3:22 took, res.length 1948 2915
queries.js?56c3:22 took, res.length 1970 2915
queries.js?56c3:22 took, res.length 1996 2915
queries.js?56c3:22 took, res.length 2016 2915
queries.js?56c3:22 took, res.length 2040 2915
queries.js?56c3:22 took, res.length 2059 2915
queries.js?56c3:22 took, res.length 2082 2915
queries.js?56c3:22 took, res.length 2105 2915
queries.js?56c3:22 took, res.length 2126 2915
queries.js?56c3:22 took, res.length 2150 2915
queries.js?56c3:22 took, res.length 2169 2915
queries.js?56c3:22 took, res.length 2193 2915
queries.js?56c3:22 took, res.length 2211 2915
queries.js?56c3:22 took, res.length 2232 2915
queries.js?56c3:22 took, res.length 2252 2915
queries.js?56c3:22 took, res.length 2295 2915
queries.js?56c3:22 took, res.length 2339 2915
queries.js?56c3:22 took, res.length 2375 2915
queries.js?56c3:22 took, res.length 2415 2915
```

**Comment by mfbx9da4** [comment]
`db.getAll` seems to produce results of about 3 seconds in the above experiment consistently - but when I use async iterators via `import('idb/with-async-ittr')` it can go up to 15 or 30 seconds for the query to resolve

**Comment by jakearchibald** [comment]
This isn't a reproducible example. `window.db` is undefined.

**Comment by mfbx9da4** [comment]
Yeah fair enough, didn't expect you to be quite so attentive. Appreciate your time 😊 I have updated the code snippet above and provided a codesandbox URL @jakearchibald 

https://codesandbox.io/s/gifted-wilbur-520eh?file=/src/index.ts:0-1642

**Comment by jakearchibald** [comment]
Thank you, I'll take a look

**Comment by jakearchibald** [comment]
> `db.getAll` seems to produce results of about 3 seconds in the above experiment consistently - but when I use async iterators via `import('idb/with-async-ittr')` it can go up to 15 or 30 seconds for the query to resolve

The reduction doesn't include any async iteration at all, so I'll ignore this for now.

> It looks like IDB serializes the `inParallel` requests. This is surprising to me as I would have thought that since theses are `readonly` transactions, IDB should be able to serve them more or less in parallel?

Right, but the creation of objects from their serialised form still needs to happen on the main thread. In your demo I'm seeing 100,000 objects being fetched and deserialised in 400ms in Chrome. Is that bad? Compared to what?

Doing it in series looks around 150ms slower than in parallel in your test. That seems expected.

Doing it without the library is around 30ms quicker. So the overhead of the library is around 3ms per transaction on an object store with 10000 items. Maybe that's something to look into, but it seems pretty small, and the library makes it easy to drop down to raw IDB for the edge cases.

The overhead seems much less in Safari. In fact it's generally quicker in Safari, which might be worth filing a crbug.com, although you'll need to state why this demo is representative.

Results in Firefox are similar to Chrome.

If I'm missing something, or if you were actually talking about async iterators, please make a reproducible example that demonstrates the things you're talking about.

**Comment by mfbx9da4** [comment]
You are absolutely correct. Thank you for looking into this. I was mislead by my timing function. My timing function was reporting that the query was taking a long time but it had nothing to do with the query. The query looked like it was taking ages to finish because the async function was taking ages to resolve.  The async function was taking ages to resolve because the main thread was busy rendering the list returned from IDB. I was memoizing each item in the list based on a weak reference to the db row which obviously changed each time it was serialized out of the database.

The root cause of the performance issues I was seeing was my shoddy code and not your library. 

Thanks again 😊 👍

**Comment by jakearchibald** [comment]
No problem!
