### ISSUE TITLE
createIndex with special character "@" in keyPath and nested objects

### ISSUE THREAD

**Issue by marcuslindblom** [jakearchibald/idb#202]
Is it possible to create an index on this key `store.createIndex('name', '@metadata.@foo.name');`

**Comment by jakearchibald** [comment]
Have you tried?

**Comment by marcuslindblom** [comment]
Oh yes, sorry. I have tested and the above throws this exception `Failed to execute 'createIndex' on 'IDBObjectStore': The keyPath argument contains an invalid key path.`. I Guess my question was a bit vague. I thought maybe it is possible to use another syntax for this, or escape the `@` sign in some way to make it work.

**Comment by jakearchibald** [comment]
It seems like keypath elements need to valid identifiers right now. Some discussion here https://github.com/w3c/IndexedDB/issues/209#issuecomment-533404075
