### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by a-ditucalan** [jakearchibald/idb#205]
HI im having an error i dont know why. any help? everytime i called the funcation for initIndexDB its always says that store not found.
![image](https://user-images.githubusercontent.com/58244709/95554839-7069ca80-0a43-11eb-96e0-c30567ed17cb.png)
![image](https://user-images.githubusercontent.com/58244709/95554860-79f33280-0a43-11eb-95bb-1d1526644087.png)

**Comment by jakearchibald** [comment]
I'm happy to help, but you need to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

A guess: You've changed the schema of your database without incrementing the version number.

Happy to reopen this once you've given me a minimal reproducible example.
