### ISSUE TITLE
Typing for openCursor and openKeyCursor should allow null for the query parameter.

### ISSUE THREAD

**Issue by cmlenz** [jakearchibald/idb#211]
The typings for the `IDBPObjectStore` and `IDBPIndex` methods `openCursor` and `openKeyCursor` should allow `null` for the `query` parameter.

This is needed for example to iterate over all values in the store in descending order:

```ts
const cursor = myObjectStore.openCursor(null, 'prev');
```

The TypeScript `lib.dom.d.ts` also explicitly mentions this in the doc comment:

> Opens a cursor over the records matching query, ordered by direction. **If query is null, all records in index are matched.**

I think the idb typings should be updated accordingly.

**Comment by jakearchibald** [comment]
Thanks for reporting this. It will be fixed in the next release.

**Comment by cmlenz** [comment]
Great, thanks for the quick fix!
