### ISSUE TITLE
storing jsonld with idb

### ISSUE THREAD

**Issue by scenaristeur** [jakearchibald/idb#213]
Hi , i would like to use idb to store json-ld like https://json-ld.org/
```
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}
```

but it seems that  keyPath does not accept '@id'

```
    const db = await openDB('Contacts', 11, {
      upgrade(db) {
        // Create a store of objects
        const store = db.createObjectStore('contacts', {
          // The 'id' property of the object will be the key.
          keyPath: '@id',
          // If it isn't explicitly set, create a value by auto incrementing.
         autoIncrement: true,
        });
        // Create an index on the 'date' property of the objects.
        store.createIndex('date', 'date');
      },
  
    });
```
 Is there a way to use keyPath : '@id' ?

![image](https://user-images.githubusercontent.com/4020744/106521334-6120f800-64de-11eb-835f-f43b92cd2872.png)
![image](https://user-images.githubusercontent.com/4020744/106521413-7dbd3000-64de-11eb-8f9a-066ba8b18255.png)

**Comment by jakearchibald** [comment]
Unfortunately keypath must be a valid identifier https://w3c.github.io/IndexedDB/#valid-key-path
