### ISSUE TITLE
Update documentation on Microsoft Edge

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [jakearchibald/idb#214]
- [ ] Based on https://github.com/jakearchibald/idb/issues/49#issuecomment-718785118, Microsoft Edge now supports `IDBIndex`, so the [corresponding section](https://github.com/jakearchibald/idb/issues/49#issuecomment-718785118) in README should be updated.
- [ ] Also, [Microsoft Edge supports `IDBObjectStore`](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore), so the [corresponding section](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore) should be updated as well.

**Comment by jakearchibald** [comment]
PRs welcome!
