### ISSUE TITLE
Error with DBSchema

### ISSUE THREAD

**Issue by danieleguglietti** [jakearchibald/idb#220]
Hello everyone! I was trying the lib and using schemas for DB typing following the reference.
The error occurs when I try to create the "connection" to the DB and create a store, the type the "createObjectStore" function expect is "never" when my interface extends DBSchema.
After a deep look, I noticed that the "KnowKeys" type excludes the string type and that's ok because we want the keys' names as type, but the interface DBSchema declares its keys as a string and making it impossible to take keys names as type...
In the reference, in the "[Typescript](https://github.com/jakearchibald/idb#typescript)" section it extends the interface to DBSchema, which is wrong causing the error mentioned above.
Am I doing wrong/have I missed something in the reference? Or this is actually a project error?

**Comment by jakearchibald** [comment]
Can you provide some code showing the issue?

**Comment by danieleguglietti** [comment]
![immagine](https://user-images.githubusercontent.com/58826513/116807163-e180e480-ab31-11eb-8374-bd7649660d13.png)
This is the schema
![immagine](https://user-images.githubusercontent.com/58826513/116807175-f3628780-ab31-11eb-9d86-eddfb28905e8.png)
And this is the error I mentioned, since DBSchema's key are marked as string

**Comment by jakearchibald** [comment]
Can you copy and paste the code so I don't have to type it out myself?

**Comment by danieleguglietti** [comment]
https://pastebin.com/JHE80WZB

**Comment by jakearchibald** [comment]
You example code works fine on [the TypeScript playground](https://www.typescriptlang.org/play?strict=true&ts=4.2.3#code/JYWwDg9gTgLgBAbzhMBTAdgEQEJwIYDOya6AwhOuqgMYzAUA0cAkjgAqZ4x4BGhqTHAGVqAC1Qg8cAL5wAZlAgg4AcmAATHioDcAKDi7g6GKihy81VHBHjJcVAA8T6dUWFiJUhPri+V1JTAAG1QTdRUALkQfX1i4AGtUAE8oghgoIwBzPTi4gDc8IIBXVCieCAgQvHQc2Ok9aV1daiDCImYXR1R1HGi4sAyCkzg0rmBqOAB9I1H0SyiO9S6e3AAfOHQioKC4AF4NraDa3wHgIatJ9S5efgBCBfZObj4CVAAeG08APhyYuFPznAAug0lAirRoAAKACUiEaBn6RR4QXGI24dAmmVCcBm3DmqBhC06Dm6vW8uViwDkcEhi2WOAAdNMQXjLHtdvtNttYeSKbk6SSVkzcdU2ZzUAB3FjE0nYGHHXLwvlQUJFKDoaVLQWM5mzSwK+F-MBIlETQhJOZAihUWgwvp8qk0mCiYAEJlXZ78dn7IqdORGbo8v58uDO13u64vKz7PASvDAeAoDDkSg0OgUD4eSRfSEqPDqAr4kAYGAESYqJgARiYvJDFKKYEyUHzBM0QbrHZx1Mht00DIgPAAVmmhDBoKgAHJ4Ytu4HcGa5gLgEJhFTQ9udzd96gqrioADyQ5HY5Vi8CK+6FcQCWSbC4oiiKmm4Rk0IVm7iSo-MmDfOkb9-XxDRDFUYDVDUwzdS5I34A1dENRxIFgOAlnMLZ4AFWVtCAA).

I'm happy to help, but you _must_ create a reduced example of the problem. I'll reopen this if you do that.
