### ISSUE TITLE
idb 6.1.0  latest version , typescript  build issue 

### ISSUE THREAD

**Issue by rsurendraidexcel** [jakearchibald/idb#223]
Typescript  , use 6.1.0   version  in angualr project , when i run project . i found this issue..

ERROR in node_modules/idb/build/esm/entry.d.ts(50,19): error TS1005: ']' expected.
node_modules/idb/build/esm/entry.d.ts(50,22): error TS1005: ';' expected.
node_modules/idb/build/esm/entry.d.ts(50,29): error TS1005: ';' expected.
node_modules/idb/build/esm/entry.d.ts(50,56): error TS1005: ';' expected.
node_modules/idb/build/esm/entry.d.ts(50,77): error TS1005: ';' expected.
node_modules/idb/build/esm/entry.d.ts(50,78): error TS1128: Declaration or statement expected.
node_modules/idb/build/esm/entry.d.ts(51,1): error TS1128: Declaration or statement expected.

but idb  6.0.0 is working  version 6.1.0 is  Breaking build

**Comment by jakearchibald** [comment]
What version of TypeScript are you using? Can you update TypeScript?

**Comment by rsurendraidexcel** [comment]
typeScript verison:  4.2.4

**Comment by jakearchibald** [comment]
Can you update TypeScript?

**Comment by jakearchibald** [comment]
3.1.6 is 3.5 years old

**Comment by jheysen** [comment]
Hello, I have the same problem in an Angular 10 project with TS 4.0.7

**Comment by jakearchibald** [comment]
Can you update TypeScript?

**Comment by jheysen** [comment]
Sadly not at the moment, same as updating Angular (that would update TS)

**Comment by jakearchibald** [comment]
Thanks. I'll look at ways of improving the support.

**Comment by rsurendraidexcel** [comment]
I  user anguar 7,   In my production 
 
I  change  : **tsconfig file like this** 

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom",
      "es6",
      "es2016",
      "es2015.core",
      "es2015.collection",
      "es2015.generator",
      "es2015.iterable",
      "es2015.promise",
      "es2015.proxy",
      "es2015.reflect",
      "es2015.symbol",
      "es2015.symbol.wellknown",
      "esnext.asynciterable"
    ]
  }
}


Fo me   Angualr 7.2  wont support    latest typescript version  3.1.6,    idb 6.1.0 version is breaking   my build

for me  6.0.0 it worked 

**package.json** 
{
 "idb": "6.0.0"
}

**Comment by jakearchibald** [comment]
Thanks for the reports everyone! I'm going to find a way to make this more compatible.

**Comment by jakearchibald** [comment]
Released as 6.1.2
