### ISSUE TITLE
Unable to open indexedDB using idb library (error thrown with no message)

### ISSUE THREAD

**Issue by juicetin** [jakearchibald/idb#243]
Hi,

Please see here (https://jsfiddle.net/adestic/gs13fpbk/) for a minimal reproducible case using sample code where I'm just trying to open the DB. The error thrown happens at the `openDB` statement before any other operations happen. In each test, I've confirmed vanilla use of the `window.indexedDB` object can open and transact against indexedDB without issues.

Expected: able to open indexedDB using idb
Observed: the open operation throws an error without any error message

Tested on:
OS: Arch Linux 5.14.16arch-1
Browsers:
- Mozilla Firefox 94.0 (64-bit)
- Google Chrome Version 94.0.4606.61
- Chromium Version 95.0.4638.69 (Official Build) Arch Linux (64-bit)

**Comment by jakearchibald** [comment]
See the error it produces:

> ReferenceError: openDB is not defined

That should give you a clue 😄 

From the README:

> ### Using external script reference
>
> ```html
> <script src="https://unpkg.com/idb/build/iife/index-min.js"></script>
> <script>
>   async function doDatabaseStuff() {
>     const db = await idb.openDB(…);
>   }
> </script>
> ```
> 
> A global, `idb`, will be created, containing all exports of the module version.

Whereas your code is not using the `idb` global. Either use the `idb` global, or destructure it:

```js
const { openDB } = idb;
```

**Comment by juicetin** [comment]
@jakearchibald apologies! 100%, I posted a JS fiddle with an unrelated and silly bug instead of what I'm actually running into inside a slightly more complex codebase and jumped to post it when I thought I reproduce the same bug. I'll open a new ticket if I can reproduce the actual bug.

The tl;dr of that one is that in a typescript context, it's importing with 
```
import { openDB, deleteDB, wrap, unwrap } from 'idb';
...
  const db = await openDB('testdb', 1, {...
```

Where the `openDB` call is within a try/catch block, but fails.
