### ISSUE TITLE
'Unhandled Promise Rejection' thrown by idb.open (again)

### ISSUE THREAD

**Issue by shadow-light** [jakearchibald/idb#245]
Re #59 I think this is an issue again due to refactoring since the problem was initially fixed.

I get `IDBFactory.open() called in an invalid security context` error reports from Safari clients even though `openDB` has a `catch()` attached. So despite handling the error, the unhandledrejection event occurs.

Version: 6.1.3

**Comment by jakearchibald** [comment]
Any idea how to reproduce this?

**Comment by shadow-light** [comment]
Using idb in an iframe in Safari and attaching a catch to the open call should trigger this I believe

**Comment by jakearchibald** [comment]
Could you create a demo of the issue?

**Comment by jakearchibald** [comment]
Closing this since no reproducible demo given. Happy to reopen if an example is given.
