### ISSUE TITLE
Is there a polyfill for indexedDB or something similar?

### ISSUE THREAD

**Issue by fingerartur** [jakearchibald/idb#249]
Situation: we are using firebase, firebase is using this library, but many of our target browsers are pretty old/bad/featureless and so they do not implement indexedDB API and therefore a bunch of firebase functionalities just does not work for us.

Is there a way to polyfill indexedDB or somehow make it work and get those firebase features such as analytics and remote-config working even on these bad browsers?

PS: I tried this polyfill https://github.com/indexeddbshim/IndexedDBShim but it didn't work

PPS: Sorry for posting a question as an `issue` :) @jakearchibald I just thought you might be the right person to turn to.

**Comment by jakearchibald** [comment]
It's not something I'm aware of, sorry (but I haven't really looked either). You'd need to figure out what storage the old browsers _do_ support, and build it on top of that.
