### ISSUE TITLE
simple import

### ISSUE THREAD

**Issue by alexisargyris** [jakearchibald/idb#25]
Trying to switch to typescript. I do

     import * as idb from 'idb';

and then:

    private readonly dbPromise = idb.open('theDbName', 1, upgradeDB => { /* etc */ });

Immediately, the editor complains that:

    Property 'open' does not exist on type 'typeof "long/path"'.

so I try:

    private readonly dbPromise = idb.default.open('theDbName', 1, upgradeDB => { /* etc */ });

which passes from the editor, but produces a run-time error:

    Cannot read property 'open' of undefined

How should this be done?

**Comment by jakearchibald** [comment]
What language is the above?

**Comment by KeithHenry** [comment]
TypeScript?

Your initial `import` statement is failing to find the path `'idb'` - how are you getting this? (npm? direct?) Does it work if you use a specific path? (like `import * as idb from './{your-path}/idb'`)

There's no `idb.default` in the TS definition so that should produce an error.

**Comment by jakearchibald** [comment]
I'm not very familiar with typescript (the TS file was contributed), but I'll accept a PR to fix the issue.

**Comment by alexisargyris** [comment]
I'm switching an existing app from javascript to typescript. This is me first such attempt. As code editor I use VS Code which started providing intellisense support for typescript very early on. So here is the situation:

I've imported idb with npm, so I assume that the statement

    import * as idb from 'idb';

should work. As noted by @KeithHenry, `idb.default.open` does not exist in the TS typings file so it should produce a run-time error and it actually does. Yet, VS Code's intellisense accepts it, while it flags as error 'idb.open', which presumably is the correct syntax.

So my questions are:

- is 'idb.open' the correct syntax?
- any idea why vs code's intellisense flags 'idb.open' as error, while it accepts 'idb.default.open'?

**Comment by jakearchibald** [comment]
idb.open is the correct syntax. I guess I'll need to learn typescript to
figure out what's wrong with the ts.

**Comment by KeithHenry** [comment]
VS Code accepts it because anything untyped in TypeScript gets treated as `any` (though you can make it throw a compile time exception instead with `noImplictAny` in you `tsconfig.json` file).

The problem is with the `import` not working and so the `idb` variable is `any` - I think the problem is with the npm setup in VS Code. Try importing each type specifically (with `import {...}` syntax) and reference the path to the npm folder - if that works then you know this is VS Code 's npm setup.

**Comment by alexisargyris** [comment]
@KeithHenry I will follow your suggestions and report back (on Monday)

**Comment by KeithHenry** [comment]
@alexisargyris try this:
```
import idb from './node_modules/idb/lib';
import { UpgradeDB, DB, Transaction } from './node_modules/idb/lib';
```

Also make sure that you're either targeting ES6 or have included a definition for `Promise`, as otherwise the idb definition fails.

**Comment by alexisargyris** [comment]
@KeithHenry Thanks for your suggestion, it points to the right direction, as far as I can tell. My difficulty doesn't seem to be related to idb typings after all. Most probably, it seems to lie somewhere between TypeScript and properly importing third-party libraries to Aurelia, the framework I use. So, I'll close this. Thanks again.
