### ISSUE TITLE
Async iterators are now supported by Edge

### ISSUE THREAD

**Issue by nornagon** [jakearchibald/idb#255]
It looks like Edge now supports async iterators: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of

Perhaps they could be folded into the main bundle now?

**Comment by yw662** [comment]
Is there still "Edge" anyway ?

**Comment by nornagon** [comment]
IMO the extra bundle size isn't worth the "huh?" when you try to use async iterators as listed in the docs but they don't work because you missed the bit where you have to import a different package. Let tree shaking work it out for folks who care about bundle size, no?

**Comment by jakearchibald** [comment]
That isn't how tree shaking works unfortunately

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/idb/pull/302
