### ISSUE TITLE
Call `openDB` with a single paramter which is an object

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [jakearchibald/idb#257]
**Is your feature request related to a problem? Please describe.**
Some dbs I want to open in multiple different places with the code. For example, in the settings component I read and write to the settings db and in the game component I read the settings. I want to reuse the code for the db name, version, and upgrade logic.

**Describe the solution you'd like**
I would like to call `openDB` like this:
```js
openDB({
  name: 'settings',
  version: 3,
  upgrade: someFn,
  blocked: someOtherFn
})
```

Then I can keep the object in one place:
```js
const settingsDbOptions = {
  name: 'settings',
  version: 3,
  upgrade: someFn,
  blocked: someOtherFn
}
```

And very conveniently open a db like:
```js
openDB(settingsDbOptions)
```

**Comment by jakearchibald** [comment]
If you really want this, I think it's best to write a wrapper function.

```js
import { openDB } from 'idb';

export function objectyOpenDB(argsObj) {
  const { name, version, ...otherOptions } = argsObj;
  return openDB(name, version, otherOptions);
}
```

Or store an array of args:

```js
import { openDB } from 'idb';

const dbArgs = ['settings', 3, {
  upgrade: someFn,
  blocked: someOtherFn
}];

openDB(...dbArgs).then((db) => {
  // …
});
```
