### ISSUE TITLE
TimeoutError: Transaction timed out due to inactivity

### ISSUE THREAD

**Issue by shardick** [jakearchibald/idb#258]
Hi,
got this error TimeoutError: Transaction timed out due to inactivity. during an update operation.

Honestly, i dont know how to reproduce. This update operation is fired every second and occasionally it fails with this error.

The code is quite simple:

```
startPersistJobInterval() {
        truckyService.writeLog('Starting interval to persist local job');
        this.persistJobInterval = setInterval(this.persistJob.bind(this), 1000);
    }

persistJob() {
        if (this.currentJob != null) {
            this.db.put('jobs', this.currentJob)
                .catch((reason) => {
                    console.log(`Error updating the current job in the local db: ${reason}`);
                });
        }
    }
```

There is a possible reason? There is something i can do to avoid it?

I store the db reference in local property so it's a long time instance, is correct? Maybe i have to open\close the database connection each time i use it?

Thanks

**Comment by jakearchibald** [comment]
I don't think I have a hope of debugging this without knowing more details, eg which browsers are firing this error. It's almost certainly an issue with IndexedDB rather than this library. I can take a further look and maybe reopen if more details are given.

**Comment by piotr-cz** [comment]
More info in Chromium bugs Issue tracker: [855624](https://bugs.chromium.org/p/chromium/issues/detail?id=855624)
