### ISSUE TITLE
Support non-browser implementations of IndexedDB

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [jakearchibald/idb#259]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use this wrapper with alternative implementations of IndexedDB. I know of three such implementations: 
  - NodeJS: [`npm:indexeddb`](https://www.npmjs.com/package/indexeddb), [`npm:indexeddbshim`](https://www.npmjs.com/package/indexeddbshim)
  - Deno: [`https://deno.land/x/indexeddb`](https://deno.land/x/indexeddb)

**Describe the solution you'd like**
I know there is `wrap` that can be used once you get your hands on an instance produced by the IndexedDB API, but currently you cannot wrap the following two lines :

https://github.com/jakearchibald/idb/blob/82cad7cf582205f773da252a2cec188922c1f801/src/entry.ts#L52

https://github.com/jakearchibald/idb/blob/82cad7cf582205f773da252a2cec188922c1f801/src/entry.ts#L98

Would be nice to have either `const {openDB} = wrap(indexedDB);` or similar, or `await openDB(name, version, {indexedDB, ...});`.

Globally defining `indexedDB` with one of those implementations is also a solution but it is not a solution I like.

**Comment by jakearchibald** [comment]
`await openDB(name, version, {indexedDB, ...})` seems reasonable, but I guess there isn't a rush to do this while `IndexedDBShim` is buggy around its microtask timing.

**Comment by make-github-pseudonymous-again** [comment]
After further inspection it seems [`npm:indexeddbshim`](https://www.npmjs.com/package/indexeddbshim) is incompatible with `idb`: the transaction automatic closing logic seems to be broken, I've tried both the browser implementation and the node implementation. Since [`npm:indexeddb`](https://www.npmjs.com/package/indexeddb) is dated and since [`https://www.npmjs.com/package/indexeddb`](https://www.npmjs.com/package/indexeddb) is based on `npm:indexeddbshim` I do not see any reasons right now to implement support.

**Comment by jakearchibald** [comment]
Agreed. Hopefully a compatible implementation will appear in future. Happy to look at this again later.
