### ISSUE TITLE
If upgrade returns a rejected promise, abort the transaction

### ISSUE THREAD

**Issue by mariusGundersen** [jakearchibald/idb#26]
I tested using an async function in the upgrade callback, but if the async function fails then the upgrade still goes through. It would be nice if the transaction is aborted in case of a failure. 

Note: this is a follow up of my question here: https://github.com/w3c/IndexedDB/issues/126

**Comment by jakearchibald** [comment]
It's possible to return a promise that outlives the upgrade transaction. Wouldn't that make this feature a bit confusing? Could you show some example code (perhaps the code that led to you writing this issue) of what you'd expect to work?

**Comment by mariusGundersen** [comment]
Yeah, it seems promises and indexedDB don't really fit perfectly together, unfortunately. 

Here is the code I'm currently working on: 
* https://github.com/mariusGundersen/Ekkiog/blob/master/src/js/storage/database.js
* https://github.com/mariusGundersen/Ekkiog/blob/master/src/js/storage/upgrade/from1.js

In `from1.js` I'm reading from the database, changing the data and then writing it back into the database, because the schema has changed. I have to wait for the `get` to return the data, and then wait for the `put` to put it back again.

**Comment by jakearchibald** [comment]
Which bit can throw without failing the transaction?

**Comment by mariusGundersen** [comment]
My code can throw 😆 

I had a bug where it threw the good old `cannot read x of undefined`, but since this exception was thrown in an async function it did not abort the transaction.

**Comment by jakearchibald** [comment]
I guess that happened while the transaction was open?

**Comment by jakearchibald** [comment]
I could solve it for the above case, and it's already solved if the above threw rather than rejected.

My only worry is it *sometimes* working, since this will always result in the DB successfully upgrading.

```js
const db = await idb.open('myDatabase', 2, async () => {
  const response = await fetch(url);
  throw Error('nah');
});
```

**Comment by mariusGundersen** [comment]
yeah, I have been thinking about that too. I'm thinking a really hacky solution would be to use a special promise subclass that keeps the transaction open until it resolves or rejects. Since promise chaining should use the same constructor as what it chains from, this might work. It might also create a monster.

**Comment by jakearchibald** [comment]
Unfortunately I don't think there's a way to keep the transaction open… aside from really awful things like writing large blobs to a tmp store.

We proposed `tx.waitUntil(promise)` to make this work, but I don't think it got the support of other browsers.

**Comment by jakearchibald** [comment]
We can look at this again when we get `waitUntil`
