### ISSUE TITLE
Issue when using the latest firebase version

### ISSUE THREAD

**Issue by crunchytoast** [jakearchibald/idb#267]
`Android Bundling failed 4326ms
While trying to resolve module `idb` from file `D:\###\node_modules\@firebase\app\dist\esm\index.esm2017.js`, the package `D:\###\node_modules\idb\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`D:\###\node_modules\idb\build\index.cjs`. Indeed, none of these files exist:`

To reproduce, initialize an expo project, npm install the latest firebase version, and import any module from firebase in the App.js file.

**Comment by jakearchibald** [comment]
I'm not familiar with Firebase. Can you give me step by step instructions. I don't know what an 'expo project' is.

**Comment by crunchytoast** [comment]
ok I'm sorry, I'll write out the full details to recreate this issue...

expo is just a helper to make react-native apps, and firebase is a popular no-sql database hosting service

`npm install --global expo-cli`

then clone the repo I just shared with you called testfirebase

to start, you run `expo install`, 
then `expo start`

It should show the error...

**Comment by crunchytoast** [comment]
I have a hunch it's more of a firebase error... since they had stopped using idb as a dependency, then just recently started using it again and have run into this issue. So I'm not sure which part of the equation has changed.

**Comment by jakearchibald** [comment]
Yeah, I think so. Can you file an issue with them and link to it here?

**Comment by crunchytoast** [comment]
https://github.com/firebase/firebase-js-sdk/issues/6253

Here's a link to an existing issue there, where people are suggesting it's a problem with metro recognizing .cjs files. Seems to be an error merry-go-round... 

If this is the case, the metro is working on a fix, and has a PR already in the works...

https://github.com/facebook/metro/pull/770

**Comment by SohelIslamImran** [comment]
Same issue
![image](https://user-images.githubusercontent.com/76745339/167845843-d24c9b17-cb8d-47ad-b5a4-19f5b88abffb.png)

**Comment by crunchytoast** [comment]
If you want a workaround, you can either downgrade your firebase version for now... or add a cjs reference in your metro.config file @SohelIslamImran

**Comment by crunchytoast** [comment]
If adding the cjs reference doesn't work, then just roll back firebase

```
npm uninstall firebase
npm install firebase@9.6.11
```

**Comment by crunchytoast** [comment]
This isn't an idb issue... it's an error in the metro bundler not recognizing cjs files, combined with idb being added as a dependency for the latest firebase version.

**Comment by mfellner** [comment]
Just commenting here for folks that may still run into the same issue as I do: 

```
Error thrown when reading from storage. Original error: (0 , _idb.openDB) is not a function. (app/storage-get).
```

https://github.com/firebase/firebase-js-sdk/issues/6253#issuecomment-1159733409

**Comment by crunchytoast** [comment]
ok I'm sorry, I'll write out the full details to recreate this issue...

expo is just a helper to make react-native apps, and firebase is a popular
no-sql database hosting service

npm install --global expo-cli

then clone the repo I just shared with you called testfirebase

to start, you run expo install,
then expo start

It should show the error...
