### ISSUE TITLE
Error when building Next.js

### ISSUE THREAD

**Issue by ValyaBabenkov** [jakearchibald/idb#271]
Good afternoon.
Ran into a problem when building an application on Next.js
It blames indexDB

"next": "^12.0.10",
"idb": "^7.0.1",
"react": "^17.0.2",
"react-dom": "^17.0.2",

Thank you
<img width="758" alt="Снимок экрана 2022-06-06 в 10 08 17" src="https://user-images.githubusercontent.com/53038415/172114983-56484511-1f11-404f-a2d1-aecd747aa769.png">

**Comment by jakearchibald** [comment]
As stated in the bug report template that you deleted:

> Bug reports without a minimal reproducible example will be closed (https://stackoverflow.com/help/minimal-reproducible-example). Ideally, the example should be accessible somewhere public, like jsbin, Glitch, jsfiddle, codepen etc etc 

I'll happily reopen this when given a reproducible example.
