### ISSUE TITLE
cursor.continuePrimaryKey is not a function??

### ISSUE THREAD

**Issue by paramsinghvc** [jakearchibald/idb#28]
I'm trying to use this function on the cursor object as per [MDN doc here](https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/continuePrimaryKey). As written, I'm using this method inside web worker but seems like it's not available. Can it be confirmed? All I want to achieve is to find a row in the idb with a given id and update one of it's fields.

**Comment by jakearchibald** [comment]
There are some recent additions to the IDB spec that I need to add to this library. However, even if I add it, it'll only work in Firefox, since that's the only browser that supports `continuePrimaryKey`. Although, from your description, it seems like you could achieve this using:

```js
const dbPromise = idb.open('your-database', 1, upgradeDB => {
  // TODO: set up database
});

// Then later...
dbPromise.then(db => {
  const tx = db.transaction('store-name', 'readwrite')
  const store = tx.objectStore('store-name');
  return store.get(key).then(result => {
    result.onOfItsFields = 'updated-value';
    store.put(result);
    return tx.complete;
  });
});
```

**Comment by jakearchibald** [comment]
Ah, I've already added `continuePrimaryKey`. I guess you were trying it in a browser that doesn't support it?

**Comment by jakearchibald** [comment]
Going to close this, reopen it if you think I've gotten the wrong end of the stick.
