### ISSUE TITLE
Aborting a Transaction

### ISSUE THREAD

**Issue by eric1234** [jakearchibald/idb#280]
This is likely not a bug, but me just not understanding how to use this library. But since I didn't see any other place to ask questions I figured I would post as an issue. Assume the following minimal reproduction:

```js
const db = await idb.openDB('db', 1, {
  upgrade(db) { db.createObjectStore('store') },
})
const tx = db.transaction('store', 'readwrite')
await tx.store.put('value', 'key')
tx.abort()
```

Obviously this is a minimal reproduction. In a real world app I would have done some additional code between the `put` and the `abort` which lead to me making the decision to rollback. I have put a [runnable version](https://jsbin.com/qozomomove/edit?html,js,console,output) of this on JSBin.

I would expect this to:

- [X] Create the object store when opening
- [X] Start a read/write transaction on that object store
- [X] Add a new record where the key is `key` and the value is `value`
- [X] Revert the record added although still leave the object store created
- [ ] Continue with no errors

The last point is where I have a problem. If you look at your browser console (not the JSBin console) you will see an exception that says "Uncaught (in promise) DOMException: AbortError". This implies there is some promise failing that I am not catching. I have tried surrounding the code with `try { ... } catch(e) {}` but still no luck. What am I missing?

**Comment by jakearchibald** [comment]
Probably tx.done?

**Comment by jakearchibald** [comment]
You probably just want to `await tx.done`, you don't need the try/catch. There can be cases where the `put` works but the overall transaction fails.

See the example in the docs https://github.com/jakearchibald/idb#txdone

```js
const db = await idb.openDB('db', 1, {
  upgrade(db) {
    db.createObjectStore('store');
  },
});
const tx = db.transaction('store', 'readwrite');
onAbortClick = () => tx.abort();
await Promise.all([tx.store.put('value', 'key'), tx.done]);
```
