### ISSUE TITLE
Can't do async data migrations in the sync upgrade function

### ISSUE THREAD

**Issue by lkarabeg** [jakearchibald/idb#281]
It seems that all methods of retrieving items from a store return a promise, which can't be awaited in the upgrade function.

Let's say my blogPost type has changed. The ID used to be a number, but is now a string, Then it would be nice to be able to do something like this:

```typescript
upgrade(db, oldVersion, newVersion, transaction) {
           const blogPosts = await db.getAll('blogPosts') // Oh, no! We can't await anything here
           db.deleteObjectStore('blogPosts')
           // Re-create the store with the new schema
           // Remap and save all the items
      }
```

It would be nice if the upgrade function was async so that this type of thing can be done.

Is there any workaround for this?

**Comment by jakearchibald** [comment]
Put `async` before `upgrade`?

**Comment by lkarabeg** [comment]
I assume upgrade is not awaited, so if there are multiple migrations and it takes a bit of time, then the database object could be put to use in application code while the store is in some intermediate state.

**Comment by jakearchibald** [comment]
It follows usual transaction rules https://github.com/jakearchibald/idb#transaction-lifetime

**Comment by lkarabeg** [comment]
Sorry if I'm missing your point, but I want to be sure the upgrade is complete before the openDB promise resolves.
 
```
const db = await openDB<AppDb>("appData", currentVersion, {
      async upgrade(db, oldVersion, newVersion, transaction) {
        // Do a ton of stuff
      },
     ...
    })
  const allItems = await db.getAll('things') // Is the upgrade certainly done by now?
```

**Comment by jakearchibald** [comment]
Yep, that's how it works

**Comment by lkarabeg** [comment]
That's amazing, thanks for your help!

**Comment by jakearchibald** [comment]
No problem! The lifetime of IDB transitions is pretty weird, unfortunately I can't really change that 😄

**Comment by piotr-cz** [comment]
Somehow I cannot make the `upgrade` method to await until it's resolved.

The callback expects return type `void` here: https://github.com/jakearchibald/idb/blob/v8.0.0/src/entry.ts#L15-L25

Looks like that the `openDB` function awaits only for the open promise, but there is no handling for upgrade promise - which just isn't supported:

https://github.com/jakearchibald/idb/blob/eb2fc14bb3588d09aaa5e86a83bf3519b06e10b3/src/entry.ts#L73-L87
