### ISSUE TITLE
Await not working on promise

### ISSUE THREAD

**Issue by anilshanbhag** [jakearchibald/idb#31]
As I understand, the calls `get`, `put` return a promise when using idb. I have the following snippet in my service worker. All it does is get an object from IndexedDB, update a property and write it back. I get an error `Uncaught SyntaxError: Unexpected identifier` for the line containing await. Wondering what is wrong ? 

```
async function updateNoteId(localid, realid) {
  return getDb.then(db => {
    const tx = db.transaction('notes', 'readwrite');
    let note = await tx.objectStore('notes').get(localid);
    note.id = realid;
    return tx.objectStore('notes').put(note);
  });
} 
```

This is more of a question, i figured posting it as an issue as people may not know of this specific library.

**Comment by KeithHenry** [comment]
The keywords async and await are basically an easy way to call promises.

If you're using `await` you don't need `then`:

```
async function updateNoteId(localid, realid) {
  const db = await getDb;
    const tx = db.transaction('notes', 'readwrite');
    let note = await tx.objectStore('notes').get(localid);
    note.id = realid;
    return await tx.objectStore('notes').put(note);
} 
```

If you want to use `await` inside and anonymous function then that needs to have the `async` keyword too, so `...then(async dB => ... await`

**Comment by jakearchibald** [comment]
Yep, exactly! The original code example is using await but not inside an async function.

More info on async/await: https://developers.google.com/web/fundamentals/getting-started/primers/async-functions

**Comment by anilshanbhag** [comment]
Thanks a lot for the quick reply :-)
