### ISSUE TITLE
window.webkitStorageInfo deprecated 

### ISSUE THREAD

**Issue by ritox842** [jakearchibald/idb#34]
Hello.

I'm using this library for couple of months and everything works great.
Lately I've started getting this warning in chrome's console : 

![upload_3_15_2017_at_6_41_08_pm](https://cloud.githubusercontent.com/assets/7280441/24188404/eeff2a88-0ee9-11e7-9428-9f3dc83c63f8.png)

I'm guessing that this warning came from this library because this is the only one witch handle my app's indexed-DB.

Is there any new version in progress that fix this issue?

**Comment by KeithHenry** [comment]
I don't think `window.webkitStorageInfo` is referenced by idb at all.

idb references `indexedDB` (not `webkitIndexedDB`) directly in the current version (https://github.com/jakearchibald/idb/blob/master/lib/idb.js lines 286 and 300)

**Comment by jakearchibald** [comment]
Yeah, the library doesn't reference the deprecated property. It's either a bug in Safari or some other library.

**Comment by ritox842** [comment]
Ok.. Thanks 👍
