### ISSUE TITLE
iterateCursor missing range parameter in typeScript

### ISSUE THREAD

**Issue by mariusGundersen** [jakearchibald/idb#35]
The [`openCursor()`](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/openCursor) method takes optional range and direction, but the `iterateCursor` method does not, according to the typescript definition. I'm guessing this is a mistake?

**Comment by jakearchibald** [comment]
Yep, the ts is wrong. Could you send me a PR for this? I'm not very familiar with TS.
