### ISSUE TITLE
Null and Undefined types in tsd with --strictNullChecks

### ISSUE THREAD

**Issue by jbrianskog** [jakearchibald/idb#39]
Looks like the tsd might need to be updated for TypeScript 2. When using --strictNullChecks the type definitions need to explicitly allow null or undefined for parameter types.

Using e.g. iterateCursor(null, "prev", callback) gives a ts compiler error because the type definition doesn't explicitly allow null.

**Comment by jakearchibald** [comment]
I don't suppose you could create a PR for this? The ts file was created by someone else, and I'm not particularly familiar with it.

**Comment by KeithHenry** [comment]
I'll take a look

**Comment by LinusU** [comment]
@jakearchibald I think this can be closed now that #40 is merged?
