### ISSUE TITLE
Browser compatibility update for Firefox, Edge & Safari

### ISSUE THREAD

**Issue by robertknight** [jakearchibald/idb#42]
Thank-you for this library Jake. I've been testing the transaction lifetime issues in current versions of browsers and I think the status has changed and the README can be updated.

I created a test case at https://gist.github.com/robertknight/462d16b46a438ab67e29301861f5d55f which tests the use of IDB + Promises for a use case that tries to read-modify-write a value in a single transaction.

The test passes in current versions of Safari, Edge & Chrome but still fails in Firefox. I filed a bug for Firefox at https://bugzilla.mozilla.org/show_bug.cgi?id=1383029 .

**Comment by MattiasBuelens** [comment]
[Firefox 60](https://developer.mozilla.org/en-US/Firefox/Releases/60) has fixed the transaction lifetime issue! 🎉 
> Promises can now be used within IndexedDB code ([bug 1193394](https://bugzilla.mozilla.org/show_bug.cgi?id=1193394)).

**Comment by jakearchibald** [comment]
I updated the readme, and included a link to a test.
