### ISSUE TITLE
UnhandledPromiseRejectionWarning when not used in a browser

### ISSUE THREAD

**Issue by alexflorisca** [jakearchibald/idb#44]
At the FT, we've started testing our service worker with the service-worker-mock (https://www.npmjs.com/package/service-worker-mock) package. We also use idb directly, but are getting loads of `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): IDB requires a browser environment` console logs. I realise this is probably just node 6+ doing this, but wondering if there's a way to silence these?

**Comment by jakearchibald** [comment]
Seems like it's ignoring the "browser" field in https://github.com/jakearchibald/idb/blob/master/package.json#L6

**Comment by alexflorisca** [comment]
I've never seen the `browser` or `typings` fields before. Looks to me as though lib/node.js is being loaded as the main script, and because it's not running in a browser, it's falling into the else clause which stubs the `open` and `delete` methods with rejected promises. Could we convert `idb.d.ts` to normal js and load it in the `else` here?

**Comment by jakearchibald** [comment]
Fixed in v4
