### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mesqueeb** [jakearchibald/idb#45]
Dear Jake,

One nice update would be to (1) add an index at the top of the Readme on which you can click to go to the chapter down below, and (2) add a chapter on the install method. Just a simple:
> "To install do `npm install idb`"

will do.

Another think I wanted to ask is that you are currently linking a post to [an article about Safari bugs](https://www.raymondcamden.com/2014/09/25/IndexedDB-on-iOS-8-Broken-Bad) from 2014... Is this still relevant now in almost 2018?

**Comment by mesqueeb** [comment]
BTW, I found your library through Max's PWA course:
https://www.udemy.com/progressive-web-app-pwa-the-complete-guide/learn/v4/t/lecture

**Comment by jakearchibald** [comment]
This is fixed in v4
