### ISSUE TITLE
Handle case when open connection gets blocked

### ISSUE THREAD

**Issue by onel** [jakearchibald/idb#47]
Sometimes in firefox the open call gets blocked and the callback sent to `idb` never gets called.
It might be helpful to add an event listener for  `request.onblocked` with a promise rejection inside.
If you think this is a good idea I can make a PR.

**Comment by puradox** [comment]
I also noticed this bug. I'll go ahead and make the PR.

**Comment by puradox** [comment]
I iterated through several APIs, I've listed my two final options below for review. So far, I am leaning towards the first option, which is simple but has a small caveat.

### 1. `idb.delete(name) throwable`

Behaves like `indexedDB.deleteDatabase`, but returns a promise.

If the database is in use (i.e. still open), an error will be thrown. Once all related database connections are closed, IndexedDB will automatically delete the database.

```js
const db = await idb.open('keyvale-store', 1, upgradeFunc);
try {
  await idb.delete('keyval-store'); // throws new Error('Database still in use')
} catch (err) {
  db.close();
}
```

This is the simplest option, simply rejecting the promise. The caveat is that users might try to delete the database again after closing all connections to it; however, deleting a non-existent database does not result in error and is harmless from what I can tell.

```js
const db = await idb.open('keyvale-store', 1, upgradeFunc);
try {
  await idb.delete('keyval-store'); // throws new Error('Database still in use')
} catch (err) {
  db.close();                       // database is deleted shortly after this call
  await idb.delete('keyval-store'); // does nothing, resolves successfully
}
```

### 2. `idb.delete(name, blockedCallback?) throwable`

Behaves like `indexedDB.deleteDatabase`, but returns a promise.
If the database is in use (i.e. still open), the callback is expected to close it.
An error will be thrown if a callback is not specified.

```js
const db = await idb.open('keyvale-store', 1, upgradeFunc);
await idb.delete('keyval-store'); // throws new Error('Database still in use')
await idb.delete('keyval-store', () => {
  db.close(); // database is deleted shortly after this call
});
```

This option is in response to the caveat of option 1, but adds the possibility of doing the following:
```js
const db = await idb.open('keyvale-store', 1, upgradeFunc);
await idb.delete('keyval-store', () => {}); // doesn't throw error, resolves successfully
```

**Comment by puradox** [comment]
I partially misread the title of this issue, my bad! The problem I've been trying to solve relates to `delete`, but this also relates to `open`. I'll go ahead and make the PR for both :smile:

**Comment by jakearchibald** [comment]
Ohh cheers, will take a look

**Comment by jakearchibald** [comment]
This is fixed in v4
