### ISSUE TITLE
Save datas inside async function

### ISSUE THREAD

**Issue by julienchazal** [jakearchibald/idb#48]
Hello,

I'm following [this tutorial](https://codelabs.developers.google.com/codelabs/workbox-indexeddb/index.html?index=..%2F..%2Findex#5) : 

I put this code inside an `async` function : 
```javascript
 if (!('indexedDB' in window)) {return null;}
  return dbPromise.then(db => {
    const tx = db.transaction('events', 'readwrite');
    const store = tx.objectStore('events');
    return Promise.all(events.map(event => store.put(event)))
    .catch(() => {
      tx.abort();
      throw Error('Events were not added to the store');
    });
  });
```
and i get `Events were not added to the store` error
Maybe it's related to #31 but i'm new to async/await and indexedDB sorry ;)
Any ideas please ?

thx

**Comment by jakearchibald** [comment]
I can't recreate this. Here's a working demo that does the same as your code above https://simple-idb-demo.glitch.me/events-db.html.

Please reopen if you can create a failing demo that shows the issue you're having.

**Comment by julienchazal** [comment]
thx i finally get it working reading another time the tutorial ;)
