### ISSUE TITLE
Library doesn't check the availibility of IDBIndex on client

### ISSUE THREAD

**Issue by ashuorg** [jakearchibald/idb#49]
Library doesn't check the availibility of IDBIndex on the client at the time of import
this make fails the bundles in the case of the clients that doesn't support it like Google Sandbox

**Comment by DavidKDeutsch** [comment]
Created PR #54.

**Comment by enguerran** [comment]
In the README.md:
>Again, these methods depend on the equivalent methods on IDBIndex, so Edge does not support getKeyFromIndex, getAllFromIndex, or getAllKeysFromIndex.

But on MDN, I see Edge supports it since v18:
https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex

Do we have to update the documentation?

**Comment by jakearchibald** [comment]
Yep!

**Comment by jakearchibald** [comment]
This seems a bit niche, and can be worked around in other ways.
