### ISSUE TITLE
Using library in angular 2+

### ISSUE THREAD

**Issue by difagume** [jakearchibald/idb#53]
I am following the Udacity course - Offline web applications

I already made `npm i idb`

In my service (user.service.ts):
`import {IDBStatic} from 'idb';`
...
`createIdbHospital () {
idb.open ('hospitaldb', 1, (upgradeDB) => {
let store = upgradeDB.createObjectStore ('users', {keyPath: '_id'});
store.createIndex ('by-name', 'name');
});
} `

but it does not work, please, I need to be able to use the library in angular, there is nothing like adding it in my service.modulo.ts or as I should do, thanks

**Comment by jakearchibald** [comment]
It should just be:

```js
import idb from 'idb';
```

**Comment by difagume** [comment]
Thank you very much Jake, I replaced `import {IDBStatic} from 'idb';` for `import idb from 'idb';` and it works
