### ISSUE TITLE
"keys()" from keyval store example from README breaks on Edge and IE

### ISSUE THREAD

**Issue by rodgobbi** [jakearchibald/idb#55]
Thanks for the library before anything, it helped me a lot to deal with IndexedDB.
I'm using the Keyval Store example you provided, with some adaptations (because I wanted many stores in a single DB), and the method `keys` was breaking in Edge and IE.
After debugging, I found that the promisified store in these browsers doesn't have the `openKeyCursor` property, only `openCursor`, but both `iterateCursor` and `iterateKeyCursor` exist, because of that the `keys` method calls `iterateKeyCursor` and results in an error.
I fixed the problem by replacing `(store.iterateKeyCursor || store.iterateCursor)` for `(store.iterateCursor || store.iterateKeyCursor)`, thought I didn't test yet on Safari, this OR expression still seems pointless for me. Should it be necessary when creating the "iterateCursor" methods in the prototype, to check if exists the corresponding "openCursor" in the `nativeObject`?
If yes, I can gladly implement that, although the indexedDB API is still obscure for me.

**Comment by jakearchibald** [comment]
Thanks! This is fixed in 2.1.2.
