### ISSUE TITLE
Support ES6 modules allowing usage of dynamic imports

### ISSUE THREAD

**Issue by myuseringithub** [jakearchibald/idb#56]
I'm using [dynamic imports](https://developers.google.com/web/updates/2017/11/dynamic-import) to load javascript libraries. Could you provide a build which exports the library ? Other choice is to use a build step to transform common js modules to ES6 modules

**Comment by jakearchibald** [comment]
The next major version will be built on top of modules. The current version supports commonjs which Rollup & Webpack should be able to handle.

**Comment by myuseringithub** [comment]
Thanks, I use Babel, will try to find a plugin for transforming Commonjs to ES6 module.

**Comment by jakearchibald** [comment]
https://www.npmjs.com/package/babel-plugin-transform-commonjs-es2015-modules might be what you're looking for.

**Comment by myuseringithub** [comment]
Trying to increase the load performance of my webapp. I used SystemJS to load the library, but it is render blocking in browsers supporting native modules.
Will try that out, thanks Jake.
