### ISSUE TITLE
Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.

### ISSUE THREAD

**Issue by Dilski** [jakearchibald/idb#58]
I am getting this error `Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.` in ios 11 safari. To my knowlege ([caniuse](https://caniuse.com/#feat=bloburls)), this is incorrect, and bloburls are supported in this browser. 

In the following code, `icimageStore.put` is where the error is thrown from. 

```javascript
    function populateIcImageTable(xml, clearIdbData, imageUrl) {

        const dbPromise = idb.open(idbHelper.databaseName, idbHelper.databaseVersionNumber, idbHelper.setupDatabase);

        let imageBlob;
        // fetch blob
        imageBlob = xml.response;

        // workout image key from the image filename
        const icimageKey = getImageKeyFromUrl(imageUrl);

        if (icimageKey === null){
            // Silently exit as we don't care if the icimage URL is invalid and its highly unlikely that it would be.
            return true;
        }

        // populate pdr table
        dbPromise.then(function (db) {
            const tx = db.transaction('icimage', 'readwrite');
            const icimageStore = tx.objectStore('icimage');

            // clear the existing data?
            if (clearIdbData){
                icimageStore.clear();
                console.log('icimage: store clear requested');
            }

            return icimageStore;

        }).then(function(icimageStore){

            // empty the table before updating it.
            if (clearIdbData) {
                console.log('icimage: store cleared');
            }

            return icimageStore.put({
                icimageKey: icimageKey,
                imageUrl: imageUrl,
                imageBlob: imageBlob

            });

        }).then(function () {

            console.log('icimage stored');

        }).catch(function(e){

            if (Raven){
                Raven.captureException(e);
            }

            console.error(e.stack);

            console.log('Error storing icimage for : '+e);
            displayNotification('danger', 'There was a problem updating the interchange image cache, please try again.', e, 'timeout');

        });

    }

```
Below is the log. `61089.JPG` is the last image and apparently it is stored correctly.

![log_censored](https://user-images.githubusercontent.com/2561789/41223653-50edef04-6d62-11e8-8bae-4d447baa81ce.jpg)

This bug may be due to my code, but it seems like an incorrect error message at least. Thanks.

**Comment by jakearchibald** [comment]
https://static-misc.glitch.me/idb-blob-test here's a little demo that stores an image blob in IDB, then pulls it back out, and displays it on the page. It appears to work on iOS 11.

Please reopen if you can create a reduced demo that fails.

**Comment by TimvanScherpenzeel** [comment]
Hi Jake,

I just tested the demo you mentioned (https://static-misc.glitch.me/idb-blob-test) on my iPhone 5S running iOS 11.4 and it throws the error mentioned by @Dilski. The screen remains blank.

![screen shot 2018-08-09 at 14 49 56](https://user-images.githubusercontent.com/11870513/43899869-8938e058-9be3-11e8-8e00-a30d6da65ff0.png)

![screen shot 2018-08-09 at 14 49 33](https://user-images.githubusercontent.com/11870513/43899875-8c77fd8a-9be3-11e8-8aa2-13c4854cb7bb.png)

**Comment by Dilski** [comment]
Just done some more testing and got no cat image on iOS 11.4.1 on an iPhone 6 (safari and chrome). We believe that it was fine in June, so it may be with a new iOS version

**Comment by jakearchibald** [comment]
Ughghghghgh it works fine in the 11.4 simulator. Is there anything you might be doing different to the simulator? A particular content blocker? A non-Safari browser?

**Comment by jakearchibald** [comment]
There's nothing I can really do about this, but I've reached out to Safari folks https://twitter.com/jaffathecake/status/1027546666721796097.

**Comment by TimvanScherpenzeel** [comment]
I tested it on the stock Safari browser in private mode which raised the error mentioned above.

Interestingly when testing it in a non-private mode a different error is raised. I am using the developer inspector in the Safari browser on my Mac to inspect the console.

![screen shot 2018-08-09 at 15 31 26](https://user-images.githubusercontent.com/11870513/43902038-53166760-9be9-11e8-8382-a4d2e5e3e8c0.png)
![screen shot 2018-08-09 at 15 29 38](https://user-images.githubusercontent.com/11870513/43902039-53310ba6-9be9-11e8-9298-c0da74b79e6f.png)

There is a different ticket in localForage that describes this issue as well: https://github.com/localForage/localForage/issues/834

**Comment by jakearchibald** [comment]
Ohh well spotted.

**Comment by tomthedev** [comment]
Hi Jake, 

I work with Dillon (Dilski) we use Sentry.io in the webapp we work with and have logged thousands of these errors but only on iOS.

Happens in Chrome iOS and Safari, heres the version spread.... 

Unhandled Promise Rejection: null

value | times_seen
-- | --
iOS 11.2.6 | 767
iOS 11.3 | 4256
iOS 11.2.2 | 19
iOS 11.1.2 | 192
iOS 11.2.5 | 467
iOS 11.2.1 | 181
iOS 11.3.1 | 506
iOS 11.4 | 2907
iOS 11.4.1 | 829


Error preparing Blob/File data to be stored in object store

value | times_seen
-- | --
iOS 11.3 | 6808
iOS 11.3.1 | 921
iOS 11.4 | 4407
iOS 11.4.1 | 385

We have had no luck replicating this on actual iPhone hardware and the test URL worked on my iPhone 6 Plus before i updated to 11.4.1. Clearing though from the data above the issue existed before 11.4.1.

**Comment by tomthedev** [comment]
Which simulator are you using?

**Comment by jakearchibald** [comment]
Just the one that comes with xcode. A college of mine can recreate the issue on a real iphone.

**Comment by jakearchibald** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=188438

**Comment by Dilski** [comment]
@jakearchibald 

Looking at [here](https://github.com/WebKit/webkit/blob/8407763bf5be3f5ff1754ab0487daa83883a84d5/Source/WebCore/Modules/indexeddb/IDBObjectStore.cpp#L328), `BlobURLs are not yet supported` is referring to BlobURLS not yet supported *in private browsing mode*. Do you think this could be related to this `Error preparing Blob/File data to be stored in object store`, or is it coming just because users are using private browsing? 

Probably a silly question, but I feel like it's worth asking.

**Comment by Lando-Loeper-Neew-Ventures** [comment]
> [@jakearchibald](https://github.com/jakearchibald)
> 
> Looking at [here](https://github.com/WebKit/webkit/blob/8407763bf5be3f5ff1754ab0487daa83883a84d5/Source/WebCore/Modules/indexeddb/IDBObjectStore.cpp#L328), `BlobURLs are not yet supported` is referring to BlobURLS not yet supported _in private browsing mode_. Do you think this could be related to this `Error preparing Blob/File data to be stored in object store`, or is it coming just because users are using private browsing?
> 
> Probably a silly question, but I feel like it's worth asking/pointing out

Thanks for pointing that out! Do this day `BlobUrls` are not supported in *private browsing mode* and it took quite a while to finding that out.
