### ISSUE TITLE
'Unhandled Promise Rejection' thrown by idb.open

### ISSUE THREAD

**Issue by vxqqb** [jakearchibald/idb#59]
Env: iOS Safari 11.1

Safari still forbids IndexedDB in iframe, so when `idb.open()` is called in an iframe, `IDBFactory.open()` function fails down, which causes the promise rejection, code debug as follows:

<img width="755" alt="code1" src="https://user-images.githubusercontent.com/33274097/41703288-627cd5b8-7565-11e8-9db2-7548d871b479.png">

`request.onupgradeneeded` throws `request is undefined` error before `idb.open()` can normally return a promise object.
That's why even i do write `idb.open().catch()` in order to catch the promise rejection, this doesn't work. The `Unhandled Promise Rejection`is thrown as follows:

<img width="829" alt="code2" src="https://user-images.githubusercontent.com/33274097/41703549-4783cd9c-7566-11e8-96c2-a917b2a76fcd.png">

I can do nothing to avoid this error console.

Plz solve this `request is undefined` error when db fails to open, and return a promise object normally.

Looking forward to your reply. Thank you.

**Comment by jakearchibald** [comment]
Fixed in 2.1.3! Thanks for reporting.

**Comment by vxqqb** [comment]
👍👍
