### ISSUE TITLE
Catching and consolidation errors

### ISSUE THREAD

**Issue by holmberd** [jakearchibald/idb#65]
Following the example on the page for having a method that sets the keyval in a store, but here with a created index having a unique constraint.

If we were to generate an error on the the uniqueness constraint and try to catch these errors, reasoning about them is proven difficult.

```js
  function set(key, val) {
    return dbPromise.then(db => {
      const tx = db.transaction('keyval', 'readwrite');
      const req = tx.objectStore('keyval').index('myIndex').put(val, key);
      return tx.complete;
    }).catch(console.error);
  }
```

Here we catch on the whole method, from the promise returned by `tx.complete`. The request returned, by trying to put the value in the store, will throw a unique index constraint error `request.onerror`, which will propagate/bubble up to the transaction causing it to abort due the failed request. 
When the transaction is aborted `transaction.error` is set to `null` and since the `tx.complete` will reject from either of the `transaction.onerror` or `transaction.onabort` events, we just catch error `null` from `transaction.onerror`. The failed request will just throw as an uncaught error.

Since transactions can fail for reasons not tied to a particular request, e.g. IO errors, there still needs to be a listener to the `transaction.onerror` event, but `transaction.onabort` seems lost in translation.

We could catch on both the request and the transaction, since the request provides a more detailed error of what caused the error being thrown, thought not guaranteed.

> Request error event not guaranteed when aborting a transaction.
> This does not always result in any error events being fired. For example if a transaction is aborted due to an error while committing the transaction, or if it was the last remaining request that failed.
> https://www.w3.org/TR/IndexedDB/#abort-transaction

Catch for all requests and transactions individually or consolidate them as an iterable where the first request failed will be caught.
```js
Promise.all([req, tx.complete]).catch(console.error);
```

**Comment by jakearchibald** [comment]
I'm not sure what's being proposed here. Is the answer:

```js
async function set(key, val) {
  const db = await dbPromise;
  const tx = db.transaction('keyval', 'readwrite');
  await tx.objectStore('keyval').index('myIndex').put(val, key);
  return tx.complete;
}
```
