### ISSUE TITLE
Support for Angular 6

### ISSUE THREAD

**Issue by nikhilsumtracker** [jakearchibald/idb#67]
How can we use this in angular 6 project?
Is there any other library?

**Comment by jakearchibald** [comment]
What is it about Angular 6 that prevents you using this library? They both just run in the browser.

**Comment by nikhilsumtracker** [comment]
There is nothing wrong with this library. I wanted to point out, this library is created to provide promises which greatly helps in angular 1, but if it could also return obsevables directly then it would be great help. 
Right now, first I have to get the promise then convert it to obsevable.

**Comment by jakearchibald** [comment]
Adding an observable implementation would increase the size of this library by a large factor. If you want to use non-standard return types that already provide conversion, do that 😄
