### ISSUE TITLE
AddAll

### ISSUE THREAD

**Issue by RMCampos** [jakearchibald/idb#70]
Hello! How can I insert an array of objects using idb? Thanks!

**Comment by RMCampos** [comment]
```
addAll(myTable, objArray) {
    return dbPromise.then(db => {
        const tx = db.transaction([myTable], 'readwrite');
        const store = tx.objectStore(myTable);
        
        objArray.forEach((obj) => {
            let request = store.add(obj);
        });
        
        return tx.complete;
    });
}
```

After some research and errors, this worked just fine!

**Comment by KeithHenry** [comment]
@RMCampos `store.add` returns a promise, and that's still potentially executing as you move to the next one.

You want them all to complete before you return, something like:

```
const running = objArray.map(o => store.add(o));
await Promise.all(running);
return tx.complete;
```

**Comment by jakearchibald** [comment]
You don't need to await all the adds, awaiting the transaction complete
will do the same thing internally. That's a feature of IDB rather than this
library.

**Comment by RMCampos** [comment]
Thanks!
