### ISSUE TITLE
Cannot open cursor on iOS with 'nextunique' direction

### ISSUE THREAD

**Issue by LillaFesues** [jakearchibald/idb#71]
#### Issue description
If `openCursor` is called with the direction `nextunique` an exception is thrown on iOS Safari:

`ERROR Error: Uncaught (in promise): UnknownError: Unable to open cursor`

#### Additional details 

- If I overwrite the attribute with `next`, the cursor is opened successfully, but that's not how it supposed to work! Any idea why this happens?

```
  function promisifyRequestCall(obj, method, args) {
    var request;
    var p = new Promise(function(resolve, reject) {
      if (method === 'openCursor' && args[1] && args[1] === 'nextunique' ) {
        args[1] = 'next'
      }
      request = obj[method].apply(obj, args);
      promisifyRequest(request).then(resolve, reject);
    });

    p.request = request;
    return p;
  }
```

**Comment by jakearchibald** [comment]
Please create a minimal reproduction using https://codesandbox.io/ or similar and I'll take a closer look.
