### ISSUE TITLE
Safari IndexedDb duplicate db

### ISSUE THREAD

**Issue by honia19** [jakearchibald/idb#72]
I created issue on stackoverflow link with screenshort
This bug reproduce only in Safari
https://stackoverflow.com/questions/53560736/indexeddb-duplicate-only-in-safari
Code: 
```
    Idb.initDb()
        .then(isUpdate => {
                console.log(isUpdate);
            }
        ).catch((error) => {
        console.log(error);
    });

    static initDb = async () => {
        const db = await idb.open(dbState.name, dbState.version, (upgradeDB) => {
            dbState.stores.forEach((store) => {
                if (!upgradeDB.objectStoreNames.contains(store)) {
                    upgradeDB.createObjectStore(store);
                    console.log('The store -', store, ' was added to db');
                }
            })
        });
    };
```

**Comment by ywen** [comment]
The issue doesn't seem to be specific to this library. I use Dexie and the same problem appears

**Comment by mlrv** [comment]
Is there any update on this? I'm seeing the same issue, just on Safari

**Comment by jakearchibald** [comment]
I suspect this is a Safari bug rather than anything to do with this library, but if someone can come up with a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and steps, I can take a look.

**Comment by mlrv** [comment]
> I suspect this is a Safari bug rather than anything to do with this library, but if someone can come up with a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and steps, I can take a look.

Hey @jakearchibald, thanks for the swift response. I also believe this is a Safari bug and has nothing to do with idb itself. It might also be just a UI bug and the browser isn't actually creating multiple databases (it should also be impossible to create two dbs with the same name I assume?), I'll see if I can find out more.

**Comment by jakearchibald** [comment]
Yeah, databases are unique per name per origin.

If there isn't any data loss associated with this, then I suspect it's just a UI bug. I guess you could look into the profile and if the information is actually duplicated.

**Comment by sachinrekhi** [comment]
I'm seeing the exact same duplicate IndexedDB issue with Safari 13.1.1 on Mac 10.15.5. My guess though is that it's an issue with Safari's IDB browser, because when I make a change to a key, that change is reflected in both versions of the databases shown in the browser, suggesting they are actually the same underlying data, not in-fact two separate databases.

**Comment by jakearchibald** [comment]
Please reopen this with a minimal reproduction, if you think it's an issue with the library rather than an issue with Safari.
