### ISSUE TITLE
Cannot install tools from Device Status

### ISSUE THREAD

**Issue by HanseSecure** [jakearchibald/idb#74]
# Issue
### Expected behaviour
Install all tools from Device Status

### Actual behaviour
Following tools cant be installed.

![issue](https://user-images.githubusercontent.com/24669088/49436649-e6eb7080-f7b9-11e8-9795-1ef92a33fc18.JPG)

following erros are happening after clicking on Install

dumpdecrypted: application crashes
all others: nothing

# Environment
### idb Version
recent from kali repos
### Workstation Operating System
Recent Kali Rolling (2018.4)
### Device iOS Version
10.2.1

**Comment by jakearchibald** [comment]
What is "Device Status"?

**Comment by dokkillo** [comment]
Same issue  here

**Comment by jakearchibald** [comment]
What is "Device Status"?

**Comment by dokkillo** [comment]
@jakearchibald  "device status", is when I connect with a Iphone Jailbreaked 5 min ago, I connect to Idb by usb, and I recive this image:

![idb1](https://user-images.githubusercontent.com/920841/52716295-c0f30100-2f9e-11e9-8fbe-84465ceee954.png)

I installed all this tools, except this 4 tools that i cant install

![idb2](https://user-images.githubusercontent.com/920841/52716294-c05a6a80-2f9e-11e9-80ff-26b55c56c85c.png)


This is the console log

![idb3](https://user-images.githubusercontent.com/920841/52716293-c05a6a80-2f9e-11e9-87f9-bee14bed5bda.png)

**Comment by jakearchibald** [comment]
I think you're talking about https://github.com/dmayer/idb, not this repo.

**Comment by dokkillo** [comment]
Ouch, sorry @jakearchibald  :(

**Comment by jakearchibald** [comment]
haha no worries. Explains why I had no idea what was going on 😄
