### ISSUE TITLE
Confusing README

### ISSUE THREAD

**Issue by pesterhazy** [jakearchibald/idb#78]
The README now to refer to the upcoming 3.0.0 version, which has breaking changes, i.e. uses the `open` method name, rather than the current version, which uses `openDb`.

This is confusing to new users getting familiar with the API. Have you considered adding a warning to the README along with a pointer to https://github.com/jakearchibald/idb/blob/b17dfbde8a47967634b347634336b4b6034edcb4/README.md ?

**Comment by jakearchibald** [comment]
3.0.0 is the current version (see https://www.npmjs.com/package/idb).

**Comment by jakearchibald** [comment]
Good point, I've pushed a tag.

**Comment by pesterhazy** [comment]
Additionally in the case of a breaking change I think it would be good to provide a pointer to an older version of the docs.

**Comment by pesterhazy** [comment]
Thank you!
