### ISSUE TITLE
Share data across devices (chrome instances)

### ISSUE THREAD

**Issue by ORESoftware** [jakearchibald/idb#79]
If a user signs into Chrome, it would be nice to sync data across devices:

https://stackoverflow.com/questions/54300633/use-chrome-storage-sync-api-in-pwa

likewise:
https://developer.chrome.com/extensions/storage

is there a way to sync data across devices using IndexedDB in Chrome or?

**Comment by jakearchibald** [comment]
Something like this would increase the size of the library by an order of magnitude, so I think it's out of scope.

I think it's the job of another library, which could be built on top of this one.
