### ISSUE TITLE
v4 feedback/suggestions

### ISSUE THREAD

**Issue by philipwalton** [jakearchibald/idb#80]
First of all, great work on new API changes in v4! I spent some time trying out the new version today, and I didn't run into any issue. I'm pretty sure we could migrate to this in Workbox once we move away from running our unit tests in a node-mock environment (where the IDB-mock library we use only supports IndexedDB v1).

Also, I really like the use of proxies to make things smaller, and having a weakmap-backed `unwrap` function is a lot nicer than `_request`, `_cursor`, `_index`, etc..

A few suggestions, which I think are definitely optional, but could provide some nice sugar and sensible defaults for folks that don't necessarily know IndexedDB best practices.

### Add some shorthand methods for common requests.

Some really common pattern with `idb` are to do things like this:

```js
// Get all entries in an object store matching a query
db.transaction('my-store').objectStore('my-store').getAll(query);

// Get the first entry in an object store via an index
db.transaction('my-store').objectStore('my-store').index('my-index').getAll(query, 1)

// Add an entry to an object store.
db.transaction('my-store', 'readwrite').objectStore('my-store').put({...});
```

There could be shorthand methods for these types of requests. E.g. something like `from()`, and `in()`, where the above would become:

```js
// `.from(store)` is shorthand for `.transaction(store).objectStore(store)`
db.from('my-store').getAll(query);

// `.from(store, index)` is shorthand for `.transaction(store).objectStore(store).index(index)`
db.from('my-store', 'my-index').getAll(query);

// `.in(store)` is shorthand for `.transaction(store, 'readwrite').objectStore(store)`
db.in('my-store').put({...});
```

### Add an open timeout

Due to [this IndexedDB issue](https://github.com/w3c/IndexedDB/issues/223) there are cases where the `openDb()` promise will never resolve. While this is a bit of an edge case, when it does happen (which I've run into several times when running tests) it's very difficult to debug.

How we solved this in our Workbox IndexedDB wrapper is to use a timeout that causes the promise to reject after 2 seconds (by default, the timeout is customizable).

I found this to be quite helpful when debugging tests, because seeing that error in the console made it much easier to spot issues.

### Make the `blocking` callback default to calling `db.close()`

Most developers (AFAIK) open connections to a database and then keep the connection open for the life of the page. While in general this is a good practice (opening can be slow), it does increase the risk that a newer version of the page in another tab will get blocked when trying to upgrade the DB.

If the `blocking` callback could call `db.close()` by default (when not set), this situation would be far less likely to occur. It'll also make the above scenario far less likely as well.

The implication is now the old page will not be able to connect to the database, but this seems better than a brand new page not being able to connect.

Of course, if this behavior is not what a developer wants, they can provide their own `blocking` callback. I think it's fairly safe to assume that anyone who specifically doesn't want the auto-close behavior is advanced enough to know how to use the `blocking` callback to suit their site's needs.

* * *

On the other hand, if you wanted to keep the core exports of `idb` really small and as true to the IndexedDB spec as possible, the `idb` library could come with another, separate module file that exports a wrapper class with some of the functionality I described above.

The wrapper could also include features like lazily opening a connection to a DB in idle periods or after the first request is made. We've found this to be really nice in service worker, where you don't necessarily want to be opening IndexedDB connection eagerly every time the service worker starts up.

Anyway, again, nice work on the update! And I'd be happy to submit PRs for any of the features I suggested here.

**Comment by jakearchibald** [comment]
Thanks for taking a look at v4. This feedback is really useful.

> Add some shorthand methods for common requests.

I've been thinking about this but I don't have a good solution in mind.

I'm not keen on the `from`/`in` methods, as they kinda sound like the same thing. It'd be better to have one method & an argument that toggles write-mode (as `transaction` works).

You could have `.from(store, mode = 'readonly')` be a shortcut for `.transaction(store, mode).objectStore(store)`, but you lose the ability to wait for the transaction to complete, which is important for writing.

My plan was to 'hoist' the various read/write methods from object stores onto the database:

```js
const val = await db.get('orders', orderId);
await db.add('orders', order);
```

Where the implementation would be…

```js
for (const getMethod of ['get', 'getAll', ...etcetc]) {
  db[getMethod] = function(storeName, ...args) {
    const tx = this.transaction(storeName);
    const store = tx.objectStore(storeName);
    return store[getMethod](...args);
  };
}

for (const setMethod of ['put', 'add', ...etcetc]) {
  db[setMethod] = function(storeName, ...args) {
    const tx = this.transaction(storeName, 'readwrite');
    const store = tx.objectStore(storeName);
    store[setMethod](...args);
    return tx.done;
  };
}
```

But, as you point out, it doesn't provide shortcuts for indexes. I'm not sure what the best way forward is here. Maybe every `getMethod` should have a corresponding `getMethod + 'Index'`, where the args are `(storeName, indexName, ...args)`? What do you think?

> Add an open timeout

I wasn't aware of that gotcha. Seems like a real design error in IDB.

With a timeout I'm worried about false positives. I'm not overly keen on putting guesswork into the library.

> Make the `blocking` callback default to calling `db.close()`

As you say, this would break the old page, so I'm not sure it's much better. Hmm. I wish we had `BroadcastChannel` everywhere, as I'd add a way for the new connection to signal for the other connections to close. At least then it's opt-in by the developer, and they acknowledge that it'd break the old pages.

**Comment by philipwalton** [comment]
> I'm not keen on the `from`/`in` methods, as they kinda sound like the same thing. It'd be better to have one method & an argument that toggles write-mode (as `transaction` works).

Yeah, the `from`/`in` reads nicely in English for those specific examples, but I agree they're probably not different enough to warrant separate methods.

> You could have `.from(store, mode = 'readonly')` be a shortcut for `.transaction(store, mode).objectStore(store)`, but you lose the ability to wait for the transaction to complete, which is important for writing.

Hmmm, I hadn't considered that implication here (that you lose the reference to the transaction). I guess that won't work for anything but the simplest use cases.

> My plan was to 'hoist' the various read/write methods from object stores onto the database:

This is effectively what we did as well in Workbox's `DBWrapper`. It works fine and is nice for these simple cases. But depending on how frequently your app calls `.transaction(store).objectStore(store)`, it may end up being more total code overall for lots of users.

Did you trying proxying this as well -- rather than enumerating all the methods? You could probably get away with it since all `readonly` methods match `/^(get|count)/` (though obviously that might not always be the case).

> But, as you point out, it doesn't provide shortcuts for indexes. I'm not sure what the best way forward is here. Maybe every `getMethod` should have a corresponding `getMethod + 'Index'`, where the args are `(storeName, indexName, ...args)`? What do you think?

With that it might be impossible to tell the difference between these cases:

```js
// 1.
.put('my-store', 'value', 'key');

// 2.
.put('my-store', 'index-name', 'value');
```

You could accept an object, something like `{store, index, count, query}`, but then you're not gaining much in terms of decreased verbosity.

Or, since you're already proxying, you could also infer the index from the method name (e.g. `getAllFromIndexName(...)`, but that may be too magical for some people.

...at this point, I think it's probably fine to punt on this for the initial v4 release :) Presumably anything you add won't be a breaking change anyway.

> I wasn't aware of that gotcha. Seems like a real design error in IDB.
>
> With a timeout I'm worried about false positives. I'm not overly keen on putting guesswork into the library.

Yeah, as I mentioned, the primary place I ran into this issue was in testing -- where it was super helpful to be able to fail fast with a descriptive error message.

Maybe it makes more sense to keep that something we have just for tests / dev-mode and not something built into a library.

> As you say, this would break the old page, so I'm not sure it's much better.

Yeah, I'm not sure which is better either.

For me, this is similar to the above in that I primarily found it useful in the context of running tests, where it's quite common to open more than one version of a database. So maybe once again this is something that should only be the default in test / dev contexts.

**Comment by jakearchibald** [comment]
@philipwalton 

> Did you trying proxying this as well -- rather than enumerating all the methods?

Implementation wise, I'd set up a trap for those methods. I think I'd list them rather than regex them. If IDB introduces a method like `getFooBarWhatever`, I wouldn't want to break that.

> With that it might be impossible to tell the difference between these cases:
> 
> ```js
> // 1.
> .put('my-store', 'value', 'key');
> 
> // 2.
> .put('my-store', 'index-name', 'value');
> ```

Ah, I mean the methods would have an "Index" suffix, so the second example would be:

```js
.getIndex('my-store', 'index-name', 'query');
```

Although, now I think about it, it would be easier to do something like:

```js
.get({ store: 'my-store' index: 'index-name' }, 'query');
// or 
.get(['my-store', 'index-name'], 'value', 'key');
```

Another options is something like `database.storeTx`, which would look like this:

```js
function storeTx(storeName, mode = 'readonly') {
  const tx = this.transaction(storeName, mode);
  const store = tx.objectStore(storeName);
  return [store, tx];
}
```

Meaning usage would be:

```js
const [store, tx] = db.storeTx('whatever', 'readwrite');
```

Although that doesn't work so well for the 1-liner case:

```js
const value = await db.storeTx('whatever')[0].getAll();
```

Yet another alternative is to make `transaction.store` a reference to the first store in the transaction:

```js
const value = await db.transaction('whatever').store.getAll();
```

That would be really easy to implement.

**Comment by philipwalton** [comment]
Of all the options discussed so far, I think my preference would be to "hoist" select `IDBObjectStore` methods onto `IDBDatabase`, and require that the first param be an object.

```js
// Get an entry for the passed key.
db.get({store: 'my-store'}, key);

// Get the first 10 items in the store via an index.
db.getAll({store: 'my-store', index: 'my-index'}, query, 10);

// Update an entry in the store
db.put({store: 'my-store'}, entry);
```

An array may be a bit terser, but I think the explicitness of an object will make the code more readable, so that's my slight preference.

**Comment by jakearchibald** [comment]
This feedback was really useful, thanks!
