### ISSUE TITLE
Observable

### ISSUE THREAD

**Issue by steida** [jakearchibald/idb#88]
Promise API is nice and all for many use-cases but can't beat Observable for syncing etc.

Maybe it's beyond scope of this project, maybe it can be a nice future feature.

Maybe something like https://dexie.org/docs/Observable/Dexie.Observable is good enough.

WDYT?

**Comment by steida** [comment]
Ha! https://googlechrome.github.io/samples/indexeddb-observers/

**Comment by jakearchibald** [comment]
Observable & observers are different things.

**Comment by jakearchibald** [comment]
In 4.0.0 I'm adding async iterators:

```js
const tx = db.transaction('store-name');
const store = tx.objectStore();

for await (const [key, value] of store) {
  // …
}
```
