### ISSUE TITLE
with-async-ittr-cjs.js still uses ESM

### ISSUE THREAD

**Issue by quasicomputational** [jakearchibald/idb#98]
Jest basically doesn't support ESM at all at the moment. Not in test files, not in their imports, not in transitive imports. The only way to use them is by transpiling, which is unpleasant as the defaults avoid going into `node_modules` (for good reason).

I had hoped that importing `idb/with-async-ittr-cjs.js` (rather than `with-async-ittr.js`) would mean that I had no need to transpile `idb`. However, the `-cjs` version still imports ESM files from `build`, making it sort of useless for me - either way I have to do transpilation, so I might as well stick with the ESM entry point.

Would it be possible to change this entrypoint so that it is all CJS, please?

**Comment by jakearchibald** [comment]
Fixed and published as 4.0.2. Thanks for reporting this!

**Comment by quasicomputational** [comment]
Thanks for the quick turnaround! Isn't that file generated by Rollup, though? I worry that the hand modifications won't stick in some future release.

**Comment by jakearchibald** [comment]
You're right. I need to do that file manually now. Fixed in 34b3649.
