### ISSUE TITLE
Async Iterators documentation and operations such as Network ops or setTimeout

### ISSUE THREAD

**Issue by matthiasg** [jakearchibald/idb#99]
I think the documentation in the README of async iterators and promises should make it more clear that, due to the nature of the IDB implementation, they are NOT behaving exactly as one would expect like other async iterators in javascript.

Most importantly when consuming the data returned from within the iterator, the consumer cannot await a network operation or some other promise which does not resolve in the next javascript loop (approx) .

e.g. this is valid: 

```javascript
  while (cursor) {
      const article = { ...cursor.value }
      console.log('ARTICLE', article)
      cursor = await cursor.continue()
}
```

this is not: 

```javascript
  while (cursor) {
      const article = { ...cursor.value }
      console.log('ARTICLE', article)
      cursor = await cursor.continue()

      await sleep(100) // or await fetch etc
}
```

Otherwise this will lead to an exception

`Uncaught (in promise) DOMException: Failed to execute 'continue' on 'IDBCursor': The transaction has finished.`

EDIT: The same would also happen when using async iterators or calling something like sleep or fetch between two calls to continue. Since the actual consumer might be some way removed from the code dealing with cursors and transactions (the loop might want to yield for example) a consumer might not be able to infer why this is happening and how to change his code.

**Comment by jakearchibald** [comment]
Isn't this covered in https://github.com/jakearchibald/idb#transaction-lifetime?

**Comment by matthiasg** [comment]
@jakearchibald i would say a separate mention linking the two pieces of information would avoid more confusion. In the top of the README about async iteration it looks as if it was a standard iterator. That there is some microtask machinery going on under the hood is not readily apparent. 

I would argue a lot of people look at indexed db api, wont like the callback nature, look for 'modern' promise/async api and find idb. They would not necessarily understand what the microtask comment of transaction lifetimes means with respect to such inner loop code.

A small comment or link to a note in the async iterator and similar places might speed things up for people trying to get going quickly.

e.g  `code in the loop must complete in the transaction lifetime for more details see here. For example awaiting a fetch or a timeout is not possible during the iteration`

**Comment by jakearchibald** [comment]
> code in the loop must complete in the transaction lifetime for more details see here

Hmm, but code outside the loop is bound by exactly the same rules.

**Comment by matthiasg** [comment]
:) when i write a standard async generator function using `for await` i can do anything i want in the loop. i can wait, sleep, network fetch etc. This is not true when iterating over cursors. so based on this internal implementation detail of the generator function the external behavior is impacted. 

So one would write code looping through a dataset as delivered via an async generator and e.g send it off to a different machine. When changing the generator function internally to use IDB instead of say loading from a rest call , the consuming code does not work anymore out of the box and will throw.

Of course this can be avoided by batching and recreating cursors internally etc but as it is now I think the documentation is implying the implementation to do something it cannot.

Anyway it is your project and I am grateful it exists, just wanted to make it more clear for newcomers to avoid pitfalls.

Cheers

**Comment by jakearchibald** [comment]
Your example in the OP isn't using `for await`.

It feels like I need to bring the transaction lifetime stuff further up in the readme and call out to it a couple of times, but I don't think it's specific to async iterators.

**Comment by matthiasg** [comment]
true both loop types are affected. `for await` and `while (cursor)` it is not specific to the iterators. should have added that case too. 

I just don't like it when changing an internal implementation detail, such as the chosen persistence method (e.g. from fetch loops to IDB cursor iterations) can cause exceptions in the consumer.
Just looking at the `for await` or `while (cursor)` or manual steps in case no loops are needed does not imply anywhere that e.g await fetch(...) will suddenly cause an exception. I asked a few people here informally whether they would guess that and they didn't and also did not see the connection to the last part of the README .

**Comment by jakearchibald** [comment]
I guess I don't see why it's clear that this will cause problems:

```js
const tx = db.transaction('counters', 'readwrite');
const val = await tx.store.get('whatever');
await fetch(…);
tx.store.put(val + 1, 'whatever');
await tx.done;
```

But it suddenly becomes unclear in this case:

```js
const tx = db.transaction('counters', 'readwrite');
for await (const cursor of tx.store) {
  cursor.update(cursor.value + 1);
  await fetch(…);
}
await tx.done;
```

I will move the warning higher in the README though.

**Comment by jakearchibald** [comment]
Does this help? https://github.com/jakearchibald/idb/compare/655cec9...0492823

**Comment by matthiasg** [comment]
The suggested README change should be enough I think.

As for the other point:

It becomes unclear because the example is too highly integrated (since its just a usage demo). An actual consumer I would write is likely to be outside. I would not want the processing of data and the reading of data from stores to be in the same function unless it was a very simplistic use case.

simplified example:

```javascript
async function *getMeSomeItems(useHttp = false) {
   if (useHttp) {
     const request = await fetch(...)
     // check etc...
     for await (const nextLine of readInLines(request)) { 
        yield nextLine
     }
   } else {
     const tx = db.transaction(storeName);

    for await (const cursor of tx.store) {
      // …
      yield readValueFromCursor(cursor)
    }
   }
}
```

consumer

```javascript
for await (const nextItem of getMeSomeItems()) {
   // .. do something with it
}
```


as long as the caller of `getMeSomeItems` does sync processing OR even uses promisified code which resolves in the same microtask basically all is ok. It stops working as soon as the caller waits for something outside of the microtask (e.g. fetch, timeout, another IDB call) and the internal implementation of `getMeSomeItems` switched to IDB instead of some other data source.



PS: Maybe I should have led with the outside use-case not the specific implementation. I tried to keep close to the source and base the argument on the fact that the generator itself in case of for await tx.store or cursor.continue is not behaving like any other typical generator I would write just because of its close coupling to IDB.

**Comment by jakearchibald** [comment]
We might at some point get a `waitUntil` to hold a transaction open, but I wonder if that would lead to antipatterns.

With your code, a long-running `fetch()` could end up holding a lock on the database a lot longer than is wise.

**Comment by matthiasg** [comment]
@jakearchibald absolutely. I am not a proponent of holding the tx open. But a library on the consumer side like this might be able to handle this transparently. Restarting cursors or doing it like some databases do it for scanning through data by not removing older data from the transaction logs (e.g elasticsearch and other databases allow 'scanning') which can allow longer 'transaction' times. Though this might not count as a transaction anymore then.

Thanks for the discussion! Appreciated. I think you can close this issue then.

**Comment by jakearchibald** [comment]
It would be possible to create an iterator that creates a transaction per iteration:

```js
async function* iterateStore(db, storeName) {
  let lastKey = undefined;
  let first = true;

  while (true) {
    const range = IDBKeyRange.lowerBound(first ? (-Infinity) : lastKey);
    first = false;

    const tx = db.transaction(storeName);
    const key = await tx.store.getKey(range);
    if (key === undefined) return;
    const value = await tx.store.get(range);
    yield { key, value };
    lastKey = key;
  }
}
```

This now works:

```js
for await (const { key, value } of iterateStore(db, 'counters')) {
  console.log(key, val);
  await fetch(…);
}
```
